# Generated by Django 5.0.6 on 2026-07-14 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticsevent",
            name="actor_type",
            field=models.CharField(
                blank=True, db_index=True, default="user", max_length=40
            ),
        ),
        migrations.AddField(
            model_name="analyticsevent",
            name="category",
            field=models.CharField(
                blank=True, db_index=True, default="engagement", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="analyticsevent",
            name="counts_toward_engagement",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name="analyticsevent",
            name="is_system_event",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="analyticsevent",
            name="source",
            field=models.CharField(
                blank=True, db_index=True, default="application", max_length=80
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["category", "occurred_at"], name="analytics_e_category_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyticsevent",
            index=models.Index(
                fields=["is_system_event", "occurred_at"], name="analytics_e_system_idx"
            ),
        ),
    ]
