# Generated by Codex on 2026-07-15

from django.db import migrations


SYSTEM_EVENT_NAMES = (
    "ai_knowledge_document_indexed",
    "ai_knowledge_document_index_failed",
    "ai_reindex_started",
    "ai_reindex_completed",
)


def backfill_system_event_classification(apps, schema_editor):
    AnalyticsEvent = apps.get_model("analytics", "AnalyticsEvent")
    AnalyticsEvent.objects.filter(name__in=SYSTEM_EVENT_NAMES).update(
        category="operations",
        source="system",
        actor_type="system",
        is_system_event=True,
        counts_toward_engagement=False,
    )
    AnalyticsEvent.objects.filter(metadata__is_system_event=True).update(
        category="operations",
        source="system",
        actor_type="system",
        is_system_event=True,
        counts_toward_engagement=False,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_analyticsevent_actor_type_analyticsevent_category_and_more"),
    ]

    operations = [
        migrations.RunPython(
            backfill_system_event_classification,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
