# Generated by Django 5.0.6 on 2026-06-19 19:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerTrack',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('short_description', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('tech', 'Tech and Engineering'), ('data_ai', 'Data and AI'), ('design', 'Design and Product'), ('business', 'Business and Marketing')], db_index=True, default='tech', max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner Friendly'), ('intermediate', 'Some Experience Needed'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('icon', models.CharField(default='code', help_text='Icon identifier used in the frontend.', max_length=50)),
                ('color', models.CharField(default='#4f46e5', help_text='Hex color for the track card.', max_length=20)),
                ('target_job_titles', models.JSONField(default=list, help_text='List of job titles this track prepares students for.')),
                ('skills_acquired', models.JSONField(default=list, help_text='List of skills students gain by completing this track.')),
                ('estimated_weeks_min', models.PositiveSmallIntegerField(default=16, help_text='Minimum estimated weeks to complete at 10 hours per week.')),
                ('estimated_weeks_max', models.PositiveSmallIntegerField(default=24, help_text='Maximum estimated weeks to complete at 10 hours per week.')),
                ('avg_salary_min', models.PositiveIntegerField(default=0, help_text='Minimum average entry salary in USD.')),
                ('avg_salary_max', models.PositiveIntegerField(default=0, help_text='Maximum average entry salary in USD.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('position', models.PositiveSmallIntegerField(db_index=True, default=0, help_text='Display order on the tracks page.')),
            ],
            options={
                'db_table': 'career_tracks',
                'ordering': ['position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TrackCourse',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveSmallIntegerField(default=0, help_text='Order within the track. Lower numbers come first.')),
                ('stage', models.IntegerField(choices=[(1, 'Foundation'), (2, 'Core Skills'), (3, 'Advanced')], default=1, help_text='1=Foundation, 2=Core Skills, 3=Advanced')),
                ('is_required', models.BooleanField(default=True, help_text='Required courses must be completed. Optional courses are recommended.')),
                ('notes', models.TextField(blank=True, default='', help_text='Guidance shown to the student about this course in the context of the track.')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_memberships', to='courses.course')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_courses', to='tracks.careertrack')),
            ],
            options={
                'db_table': 'track_courses',
                'ordering': ['position'],
                'indexes': [models.Index(fields=['track', 'stage', 'position'], name='track_cours_track_i_3def17_idx')],
                'unique_together': {('track', 'course')},
            },
        ),
        migrations.CreateModel(
            name='UserTrackEnrollment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_stage', models.IntegerField(choices=[(1, 'Foundation'), (2, 'Core Skills'), (3, 'Advanced')], default=1)),
                ('courses_completed', models.PositiveSmallIntegerField(default=0)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='tracks.careertrack')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_track_enrollments',
                'indexes': [models.Index(fields=['user', 'is_completed'], name='user_track__user_id_c8df82_idx')],
                'unique_together': {('user', 'track')},
            },
        ),
    ]
