# Generated by Django 5.0.6 on 2026-07-01 14:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='portfolio',
            new_name='portfolios_user_id_f89dea_idx',
            old_name='portfolios_user_idx',
        ),
        migrations.RenameIndex(
            model_name='portfolio',
            new_name='portfolios_visibil_dedb38_idx',
            old_name='portfolios_visibility_exp_idx',
        ),
        migrations.RenameIndex(
            model_name='portfolio',
            new_name='portfolios_desired_ef3e87_idx',
            old_name='portfolios_desired_role_idx',
        ),
        migrations.RenameIndex(
            model_name='portfolioproject',
            new_name='portfolio_p_portfol_fa537c_idx',
            old_name='portfolio_projects_portfolio_idx',
        ),
        migrations.RenameIndex(
            model_name='portfolioproject',
            new_name='portfolio_p_portfol_418bca_idx',
            old_name='portfolio_projects_featured_idx',
        ),
        migrations.RenameIndex(
            model_name='portfolioskill',
            new_name='portfolio_s_portfol_4477b3_idx',
            old_name='portfolio_skills_portfolio_idx',
        ),
        migrations.RenameIndex(
            model_name='portfolioskill',
            new_name='portfolio_s_name_5d3f1b_idx',
            old_name='portfolio_skills_name_idx',
        ),
        migrations.RenameIndex(
            model_name='resume',
            new_name='resumes_user_id_23a48f_idx',
            old_name='resumes_user_idx',
        ),
        migrations.RenameIndex(
            model_name='resume',
            new_name='resumes_target__8adedd_idx',
            old_name='resumes_target_role_idx',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='preferred_work_country',
            field=models.CharField(blank=True, db_index=True, default='GN', help_text='ISO 3166-1 alpha-2 code of preferred work country. e.g. GN, FR, US', max_length=2),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='relocation_willingness',
            field=models.CharField(choices=[('no', 'Not willing to relocate'), ('local', 'Local only'), ('national', 'Within country'), ('regional', 'Within region'), ('global', 'Open to relocation globally')], db_index=True, default='no', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='remote_preference',
            field=models.CharField(choices=[('onsite', 'On-site only'), ('hybrid', 'Hybrid'), ('remote', 'Remote only'), ('flexible', 'Flexible')], db_index=True, default='flexible', max_length=20),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='desired_role',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Target job title for matching. e.g. Backend Developer', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='headline',
            field=models.CharField(blank=True, default='', help_text='Short professional tagline. e.g. Full-Stack Developer | Python and React', max_length=200),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='demo_video_url',
            field=models.URLField(blank=True, default='', help_text='Link to a demo video (YouTube, Loom, or HLS URL).', max_length=500),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='gallery_urls',
            field=models.JSONField(default=list, help_text='List of screenshot/image URLs for the project gallery.'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Featured projects appear at the top of the portfolio.'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='tech_stack',
            field=models.JSONField(default=list, help_text="List of technologies used. e.g. ['Python', 'Django', 'PostgreSQL']"),
        ),
        migrations.AlterField(
            model_name='portfolioskill',
            name='category',
            field=models.CharField(blank=True, default='', help_text='e.g. Programming Language, Framework, Tool, Soft Skill', max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolioskill',
            name='source_id',
            field=models.UUIDField(blank=True, help_text='ID of the track or course this skill was imported from.', null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.JSONField(default=list, help_text='List of education entries.'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.JSONField(default=list, help_text='List of experience entries.'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='pdf_url',
            field=models.URLField(blank=True, default='', help_text='S3 URL of the last generated PDF.', max_length=500),
        ),
        migrations.AlterField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='Professional summary or objective statement.'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='target_role',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Target job title. Used for AI recommendations.', max_length=200),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(blank=True, default='', help_text='e.g. Software Engineer Resume or Data Analyst CV', max_length=200),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['preferred_work_country'], name='portfolios_preferr_b49774_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['relocation_willingness'], name='portfolios_relocat_c8a5bd_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['remote_preference'], name='portfolios_remote__ef8666_idx'),
        ),
    ]
