# Generated by Django 5.0.6 on 2026-07-03 00:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0002_add_global_work_preferences"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerResume",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("summary", models.TextField(blank=True, default="")),
                (
                    "target_role",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=200
                    ),
                ),
                ("education", models.JSONField(blank=True, default=list)),
                ("experience", models.JSONField(blank=True, default=list)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_resumes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "career_resumes",
                "ordering": ["-is_default", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="PortfolioProjectMedia",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("document", "Document"),
                        ],
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(max_length=1000)),
                ("title", models.CharField(blank=True, default="", max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("unlisted", "Unlisted"),
                            ("private", "Private"),
                        ],
                        db_index=True,
                        default="public",
                        max_length=10,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="careers.portfolioproject",
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_project_media",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("viewed_by_recruiter", "Viewed by Recruiter"),
                            ("downloaded", "Downloaded"),
                            ("used_for_application", "Used for Application"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="career_resume_analytics_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="careers.careerresume",
                    ),
                ),
            ],
            options={
                "db_table": "career_resume_analytics",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_url", models.URLField(max_length=1000)),
                ("file_name", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("is_private", models.BooleanField(db_index=True, default=True)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="careers.careerresume",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="career_resume_files_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "career_resume_files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version_number", models.PositiveIntegerField(default=1)),
                ("snapshot", models.JSONField(blank=True, default=dict)),
                (
                    "change_summary",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="careers.careerresume",
                    ),
                ),
            ],
            options={
                "db_table": "career_resume_versions",
                "ordering": ["-version_number"],
            },
        ),
        migrations.AddIndex(
            model_name="careerresume",
            index=models.Index(
                fields=["user", "is_default"], name="career_resume_user_default_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="careerresume",
            index=models.Index(
                fields=["user", "is_archived"], name="career_resume_arch_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="portfolioprojectmedia",
            index=models.Index(
                fields=["project", "visibility"], name="pf_media_proj_vis_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="resumeversion",
            unique_together={("resume", "version_number")},
        ),
    ]
