# Generated by Django 5.0.6 on 2026-07-03 00:36

import apps.careers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0003_careerresume_portfolioprojectmedia_resumeanalytics_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioprojectmedia",
            name="content_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="portfolioprojectmedia",
            name="file",
            field=models.FileField(
                blank=True,
                default="",
                upload_to=apps.careers.models.portfolio_media_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="portfolioprojectmedia",
            name="file_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="portfolioprojectmedia",
            name="file_size",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="portfolioprojectmedia",
            name="is_featured",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="resumefile",
            name="file",
            field=models.FileField(
                blank=True,
                default="",
                upload_to=apps.careers.models.resume_file_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="resumefile",
            name="file_size",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="portfolioprojectmedia",
            name="url",
            field=models.URLField(blank=True, default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="resumefile",
            name="file_url",
            field=models.URLField(blank=True, default="", max_length=1000),
        ),
    ]
