# Generated by Django 5.0.6 on 2026-07-04 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_platform", "0002_aievaluationdataset_and_more"),
        ("careers", "0005_resumeaireview"),
        ("jobs", "0009_jobapplicationquestion_jobapplicationanswer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PortfolioAIReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("portfolio_review", "Portfolio Review"),
                            ("project_review", "Project Review"),
                            ("github_review", "GitHub Review"),
                            ("skill_extraction", "Skill Extraction"),
                            ("job_match", "Job Match"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "prompt_version",
                    models.CharField(
                        default="portfolio-intelligence-v1", max_length=40
                    ),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=12),
                ),
                (
                    "overall_score",
                    models.PositiveSmallIntegerField(db_index=True, default=0),
                ),
                ("project_score", models.PositiveSmallIntegerField(default=0)),
                ("github_score", models.PositiveSmallIntegerField(default=0)),
                ("match_score", models.PositiveSmallIntegerField(default=0)),
                ("confidence", models.PositiveSmallIntegerField(default=0)),
                ("extracted_skills", models.JSONField(blank=True, default=dict)),
                ("missing_skills", models.JSONField(blank=True, default=list)),
                ("technology_stack", models.JSONField(blank=True, default=list)),
                ("strengths", models.JSONField(blank=True, default=list)),
                ("weaknesses", models.JSONField(blank=True, default=list)),
                ("suggestions", models.JSONField(blank=True, default=list)),
                ("action_items", models.JSONField(blank=True, default=list)),
                ("report", models.JSONField(blank=True, default=dict)),
                ("summary", models.TextField(blank=True, default="")),
                (
                    "ai_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolio_reviews",
                        to="ai_platform.airequest",
                    ),
                ),
                (
                    "ai_response",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolio_reviews",
                        to="ai_platform.airesponse",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="portfolio_ai_reviews",
                        to="jobs.joblisting",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_reviews",
                        to="careers.portfolio",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_reviews",
                        to="careers.portfolioproject",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portfolio_ai_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "portfolio_ai_reviews",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "review_type", "created_at"],
                        name="portfolio_ai_user_type_idx",
                    ),
                    models.Index(
                        fields=["portfolio", "review_type", "created_at"],
                        name="portfolio_ai_port_type_idx",
                    ),
                ],
            },
        ),
    ]
