# Generated by Django 5.0.6 on 2026-06-20 06:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('quiz_passed', 'Quiz Passed'), ('certificate_issued', 'Certificate Issued'), ('track_stage_advanced', 'Track Stage Advanced'), ('discussion_reply', 'Discussion Reply'), ('new_job_match', 'New Job Match'), ('welcome', 'Welcome')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=500)),
                ('action_url', models.CharField(blank=True, default='', help_text='Relative URL the user is taken to when they click the notification.', max_length=300)),
                ('payload', models.JSONField(default=dict, help_text='Type-specific data for rendering the notification.')),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_583549_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_2c3905_idx')],
            },
        ),
    ]
