# Generated by Django 5.0.6 on 2026-07-02 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("quiz_passed", "Quiz Passed"),
                    ("certificate_issued", "Certificate Issued"),
                    ("track_stage_advanced", "Track Stage Advanced"),
                    ("discussion_reply", "Discussion Reply"),
                    ("new_job_match", "New Job Match"),
                    ("welcome", "Welcome"),
                    ("application_received", "Application Received"),
                    ("application_stage_changed", "Application Stage Changed"),
                    ("interview_scheduled", "Interview Scheduled"),
                    ("interview_updated", "Interview Updated"),
                    ("offer_sent", "Offer Sent"),
                    ("offer_accepted", "Offer Accepted"),
                    ("offer_declined", "Offer Declined"),
                    ("recruiter_invited", "Recruiter Invited"),
                    (
                        "organization_invitation_accepted",
                        "Organization Invitation Accepted",
                    ),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
