# Generated by Django 5.0.6 on 2026-07-03 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_emaildelivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaildelivery",
            name="provider_message_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="emaildelivery",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("sent", "Sent"),
                    ("skipped", "Skipped"),
                    ("failed", "Failed"),
                    ("retrying", "Retrying"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
