# Generated by Django 5.0.6 on 2026-07-03 12:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


CATEGORY_BY_TYPE = {
    "quiz_passed": "course_updates",
    "certificate_issued": "certificates",
    "track_stage_advanced": "course_updates",
    "discussion_reply": "course_updates",
    "new_job_match": "job_alerts",
    "welcome": "security",
    "application_received": "applications",
    "application_stage_changed": "applications",
    "interview_scheduled": "interviews",
    "interview_updated": "interviews",
    "offer_sent": "offers",
    "offer_accepted": "offers",
    "offer_declined": "offers",
    "recruiter_invited": "recruiter_invites",
    "organization_invitation_accepted": "organization_invites",
}


def backfill_notification_categories(apps, schema_editor):
    Notification = apps.get_model("notifications", "Notification")
    EmailDelivery = apps.get_model("notifications", "EmailDelivery")
    for notification_type, category in CATEGORY_BY_TYPE.items():
        Notification.objects.filter(notification_type=notification_type).update(category=category)
        EmailDelivery.objects.filter(notification__notification_type=notification_type).update(category=category)


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_emaildelivery_provider_message_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="emaildelivery",
            name="body_html",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="emaildelivery",
            name="category",
            field=models.CharField(
                choices=[
                    ("job_alerts", "Job Alerts"),
                    ("applications", "Applications"),
                    ("interviews", "Interviews"),
                    ("offers", "Offers"),
                    ("organization_invites", "Organization Invites"),
                    ("recruiter_invites", "Recruiter Invites"),
                    ("course_updates", "Course Updates"),
                    ("certificates", "Certificates"),
                    ("marketing", "Marketing"),
                    ("security", "Security"),
                ],
                db_index=True,
                default="security",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="emaildelivery",
            name="failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("job_alerts", "Job Alerts"),
                    ("applications", "Applications"),
                    ("interviews", "Interviews"),
                    ("offers", "Offers"),
                    ("organization_invites", "Organization Invites"),
                    ("recruiter_invites", "Recruiter Invites"),
                    ("course_updates", "Course Updates"),
                    ("certificates", "Certificates"),
                    ("marketing", "Marketing"),
                    ("security", "Security"),
                ],
                db_index=True,
                default="security",
                max_length=40,
            ),
        ),
        migrations.CreateModel(
            name="EmailSuppression",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("job_alerts", "Job Alerts"),
                            ("applications", "Applications"),
                            ("interviews", "Interviews"),
                            ("offers", "Offers"),
                            ("organization_invites", "Organization Invites"),
                            ("recruiter_invites", "Recruiter Invites"),
                            ("course_updates", "Course Updates"),
                            ("certificates", "Certificates"),
                            ("marketing", "Marketing"),
                            ("security", "Security"),
                        ],
                        db_index=True,
                        default="",
                        max_length=40,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=100)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_suppressions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_suppressions",
                "indexes": [
                    models.Index(
                        fields=["email", "category", "is_active"],
                        name="email_suppression_lookup_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("job_alerts", "Job Alerts"),
                            ("applications", "Applications"),
                            ("interviews", "Interviews"),
                            ("offers", "Offers"),
                            ("organization_invites", "Organization Invites"),
                            ("recruiter_invites", "Recruiter Invites"),
                            ("course_updates", "Course Updates"),
                            ("certificates", "Certificates"),
                            ("marketing", "Marketing"),
                            ("security", "Security"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_preferences",
                "indexes": [
                    models.Index(
                        fields=["user", "category"], name="notif_pref_user_category_idx"
                    )
                ],
                "unique_together": {("user", "category")},
            },
        ),
        migrations.CreateModel(
            name="NotificationUnsubscribeToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("job_alerts", "Job Alerts"),
                            ("applications", "Applications"),
                            ("interviews", "Interviews"),
                            ("offers", "Offers"),
                            ("organization_invites", "Organization Invites"),
                            ("recruiter_invites", "Recruiter Invites"),
                            ("course_updates", "Course Updates"),
                            ("certificates", "Certificates"),
                            ("marketing", "Marketing"),
                            ("security", "Security"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(db_index=True, max_length=128, unique=True),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_unsubscribe_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_unsubscribe_tokens",
                "indexes": [
                    models.Index(
                        fields=["email", "category", "expires_at"],
                        name="notif_unsub_email_cat_idx",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill_notification_categories, migrations.RunPython.noop),
    ]
