# Generated by Django 5.0.6 on 2026-07-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0005_emaildelivery_body_html_emaildelivery_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("quiz_passed", "Quiz Passed"),
                    ("certificate_issued", "Certificate Issued"),
                    ("track_stage_advanced", "Track Stage Advanced"),
                    ("discussion_reply", "Discussion Reply"),
                    ("new_job_match", "New Job Match"),
                    ("welcome", "Welcome"),
                    ("application_received", "Application Received"),
                    ("application_stage_changed", "Application Stage Changed"),
                    ("interview_scheduled", "Interview Scheduled"),
                    ("interview_updated", "Interview Updated"),
                    ("offer_sent", "Offer Sent"),
                    ("offer_accepted", "Offer Accepted"),
                    ("offer_declined", "Offer Declined"),
                    ("recruiter_invited", "Recruiter Invited"),
                    (
                        "organization_invitation_accepted",
                        "Organization Invitation Accepted",
                    ),
                    ("academic_review_assigned", "Academic Review Assigned"),
                    ("academic_review_due_soon", "Academic Review Due Soon"),
                    ("academic_review_overdue", "Academic Review Overdue"),
                    ("academic_changes_requested", "Academic Changes Requested"),
                    ("academic_instructor_responded", "Academic Instructor Responded"),
                    ("academic_content_resubmitted", "Academic Content Resubmitted"),
                    ("academic_content_approved", "Academic Content Approved"),
                    ("academic_content_rejected", "Academic Content Rejected"),
                    ("publication_blocked", "Publication Blocked"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
