# Generated by Django 5.0.6 on 2026-06-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresettoken',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='github_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='True after the user clicks the verification link in their email.'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_public_profile',
            field=models.BooleanField(default=True, help_text='If true, profile is visible to recruiters and public.'),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_headline',
            field=models.CharField(blank=True, default='', help_text='Short professional tagline shown on profile.', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.SlugField(blank=True, help_text='Public profile URL slug. e.g. john-doe', null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
