# Generated by Django 5.0.6 on 2026-06-30 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0003_remove_passwordresettoken_user_user_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_country',
            field=models.CharField(blank=True, default='GN', help_text='Country where the user currently lives.', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='locale',
            field=models.CharField(blank=True, default='fr-GN', help_text='Full locale string. e.g. fr-GN, en-US', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 country code. e.g. GN', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_currency',
            field=models.CharField(blank=True, default='GNF', help_text='ISO 4217 currency code. e.g. GNF, USD', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, default='fr', help_text='BCP 47 language code. e.g. fr, en, ar', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, default='Africa/Conakry', help_text='IANA timezone. e.g. Africa/Conakry, Europe/Paris', max_length=50),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['current_country'], name='users_current_b6663c_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['preferred_language'], name='users_preferr_cf0f22_idx'),
        ),
    ]
