# Generated by Django 5.0.6 on 2026-07-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_add_global_locale_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("instructor", "Instructor"),
                    ("mentor", "Mentor"),
                    ("recruiter", "Recruiter"),
                    ("company_admin", "Company Admin"),
                    ("university_admin", "University Admin"),
                    ("content_moderator", "Content Moderator"),
                    ("finance_admin", "Finance Admin"),
                    ("platform_admin", "Platform Admin"),
                    ("super_admin", "Super Admin"),
                    ("admin", "Admin"),
                ],
                db_index=True,
                default="student",
                max_length=20,
            ),
        ),
    ]
