# Generated by Django 5.0.6 on 2026-07-03 12:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPrivacySettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("public_profile", models.BooleanField(db_index=True, default=True)),
                ("recruiter_resume_visibility", models.BooleanField(default=True)),
                ("recruiter_portfolio_visibility", models.BooleanField(default=True)),
                ("open_to_work", models.BooleanField(db_index=True, default=False)),
                ("allow_recruiter_contact", models.BooleanField(default=True)),
                ("allow_analytics", models.BooleanField(default=True)),
                ("allow_ai_analysis", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="privacy_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_privacy_settings",
                "indexes": [
                    models.Index(
                        fields=["public_profile", "open_to_work"],
                        name="user_privacy_public_work_idx",
                    )
                ],
            },
        ),
    ]
