# Generated by Django 5.0.6 on 2026-07-01 18:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustScoreLog',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_type', models.CharField(choices=[('instructor', 'Instructor'), ('recruiter', 'Recruiter'), ('organization', 'Organization'), ('learner', 'Learner')], db_index=True, max_length=30)),
                ('subject_id', models.UUIDField(db_index=True)),
                ('previous_score', models.SmallIntegerField()),
                ('new_score', models.SmallIntegerField()),
                ('change_value', models.SmallIntegerField(help_text='Positive or negative change applied.')),
                ('change_reason', models.CharField(choices=[('email_verified', 'Email Verified'), ('profile_complete', 'Profile Complete'), ('identity_submitted', 'Identity Document Submitted'), ('identity_verified', 'Identity Verified'), ('teaching_demo_submitted', 'Teaching Demo Submitted'), ('teaching_demo_approved', 'Teaching Demo Approved'), ('first_course_published', 'First Course Published'), ('rating_above_4', 'Rating Above 4.0'), ('company_verified', 'Company Verified'), ('company_email_verified', 'Company Email Verified'), ('registration_submitted', 'Registration Document Submitted'), ('website_verified', 'Website Verified'), ('enterprise_level', 'Enterprise Level Granted'), ('first_job_posted', 'First Job Posted'), ('first_certificate', 'First Certificate Earned'), ('portfolio_complete', 'Portfolio Has 2+ Projects'), ('resume_created', 'Resume Created'), ('complaint_received', 'Complaint Received'), ('suspended', 'Account Suspended'), ('manual_adjustment', 'Manual Adjustment by Staff'), ('suspicious_activity', 'Suspicious Activity Detected')], db_index=True, max_length=50)),
                ('calculated_by', models.CharField(default='system', help_text='system or staff', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null when calculated by the system.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trust_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trust_score_logs',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['subject_type', 'subject_id'], name='trust_score_subject_5ee1ad_idx'), models.Index(fields=['change_reason'], name='trust_score_change__47c5be_idx'), models.Index(fields=['performed_at'], name='trust_score_perform_786b02_idx')],
            },
        ),
    ]
