# Generated by Django 5.0.6 on 2026-07-01 18:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityVerificationDocument',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_type', models.CharField(choices=[('instructor', 'Instructor'), ('recruiter', 'Recruiter'), ('organization', 'Organization')], db_index=True, max_length=30)),
                ('owner_id', models.UUIDField(db_index=True)),
                ('document_type', models.CharField(choices=[('national_id', 'National ID Card'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('residence_permit', 'Residence Permit'), ('government_id_other', 'Other Government ID'), ('business_registration', 'Business Registration Certificate'), ('tax_registration', 'Tax Registration Document'), ('business_license', 'Business License'), ('company_doc_other', 'Other Company Document'), ('teaching_demo', 'Teaching Demo Video')], max_length=30)),
                ('s3_bucket', models.CharField(max_length=100)),
                ('s3_key', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes.')),
                ('mime_type', models.CharField(max_length=100)),
                ('is_encrypted', models.BooleanField(default=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('verified_until', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('staff_notes', models.TextField(blank=True, default='')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identity_verification_documents',
                'indexes': [models.Index(fields=['owner_type', 'owner_id'], name='identity_ve_owner_t_efe594_idx'), models.Index(fields=['owner_type', 'owner_id', 'is_active'], name='identity_ve_owner_t_61a5cd_idx'), models.Index(fields=['document_type'], name='identity_ve_documen_ab2f22_idx')],
            },
        ),
        migrations.CreateModel(
            name='VerificationAction',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('instructor', 'Instructor'), ('recruiter', 'Recruiter'), ('organization', 'Organization')], db_index=True, max_length=30)),
                ('target_id', models.UUIDField(db_index=True)),
                ('action', models.CharField(choices=[('submitted', 'Submitted for Review'), ('assigned', 'Assigned to Reviewer'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('reinstated', 'Reinstated'), ('more_info_requested', 'More Information Requested'), ('priority_changed', 'Priority Changed'), ('document_uploaded', 'Document Uploaded'), ('document_deleted', 'Document Deleted'), ('signed_url_generated', 'Document Accessed via Signed URL')], db_index=True, max_length=30)),
                ('previous_status', models.CharField(blank=True, default='', max_length=30)),
                ('new_status', models.CharField(blank=True, default='', max_length=30)),
                ('reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('device', models.CharField(blank=True, default='', max_length=200)),
                ('browser', models.CharField(blank=True, default='', max_length=200)),
                ('country', models.CharField(blank=True, default='', max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_actions',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='verificatio_target__0ad1e4_idx'), models.Index(fields=['actor', 'performed_at'], name='verificatio_actor_i_d3d3ba_idx'), models.Index(fields=['action', 'performed_at'], name='verificatio_action_812014_idx')],
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject_type', models.CharField(choices=[('instructor', 'Instructor'), ('recruiter', 'Recruiter'), ('organization', 'Organization')], db_index=True, max_length=30)),
                ('subject_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('more_info_required', 'More Information Required')], db_index=True, default='submitted', max_length=30)),
                ('priority', models.CharField(choices=[('high', 'High Priority'), ('normal', 'Normal'), ('low', 'Low Priority')], db_index=True, default='normal', max_length=20)),
                ('priority_reason', models.CharField(blank=True, default='', help_text='e.g. paid_instructor, enterprise_company, university', max_length=100)),
                ('applicant_notes', models.TextField(blank=True, default='', help_text='Notes submitted by the applicant during submission.')),
                ('reviewer_notes', models.TextField(blank=True, default='', help_text='Notes written by the reviewer for the applicant to read.')),
                ('internal_notes', models.TextField(blank=True, default='', help_text='Internal administrative notes. Never shown to applicant.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests_assigned', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_requests_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_requests',
                'ordering': ['-priority', 'submitted_at'],
                'indexes': [models.Index(fields=['subject_type', 'subject_id'], name='verificatio_subject_66e4a0_idx'), models.Index(fields=['status', 'priority'], name='verificatio_status_117853_idx'), models.Index(fields=['assigned_to', 'status'], name='verificatio_assigne_ad9f5c_idx')],
            },
        ),
    ]
