# Generated by Django 5.0.6 on 2026-07-02 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("verification", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="verificationaction",
            options={
                "get_latest_by": ["performed_at", "created_at"],
                "ordering": ["-performed_at", "-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="verificationaction",
            name="performed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
