# Generated by Django 5.0.6 on 2026-06-19 06:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cert_number', models.CharField(db_index=True, help_text='Public identifier. Format: TC-XXXXXXXXXX', max_length=20, unique=True)),
                ('pdf_url', models.URLField(blank=True, default='', help_text='S3 URL of the generated PDF certificate.', max_length=500)),
                ('is_revoked', models.BooleanField(db_index=True, default=False, help_text='Revoked certificates still exist but show as invalid on verification.')),
                ('revoked_reason', models.TextField(blank=True, default='')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='courses.course')),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='certificate', to='courses.enrollment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'certificates',
                'indexes': [models.Index(fields=['user', 'is_revoked'], name='certificate_user_id_7e36c1_idx'), models.Index(fields=['cert_number'], name='certificate_cert_nu_24abb7_idx')],
            },
        ),
    ]
