# Generated by Django 5.0.6 on 2026-06-20 04:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorConversation',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_tokens_used', models.PositiveIntegerField(default=0)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_conversations', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tutor_conversations',
            },
        ),
        migrations.CreateModel(
            name='TutorMessage',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('content', models.TextField()),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_tutor.tutorconversation')),
            ],
            options={
                'db_table': 'tutor_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tutorconversation',
            index=models.Index(fields=['user', 'lesson'], name='tutor_conve_user_id_6d60a4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tutorconversation',
            unique_together={('user', 'lesson')},
        ),
        migrations.AddIndex(
            model_name='tutormessage',
            index=models.Index(fields=['conversation', 'created_at'], name='tutor_messa_convers_24becb_idx'),
        ),
    ]
