# Generated by Django 5.0.6 on 2026-06-19 06:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRating',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stars', models.PositiveSmallIntegerField(help_text='Rating from 1 to 5.')),
                ('review', models.TextField(blank=True, default='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_ratings',
                'indexes': [models.Index(fields=['course', 'stars'], name='course_rati_course__c97a41_idx')],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answers', models.JSONField(help_text="Dict mapping question_id (str) to selected_index (int). Example: {'uuid': 2}")),
                ('score', models.PositiveSmallIntegerField(help_text='Number of correct answers.')),
                ('total_questions', models.PositiveSmallIntegerField()),
                ('percentage', models.PositiveSmallIntegerField(help_text='Score as a percentage rounded to nearest integer.')),
                ('passed', models.BooleanField(db_index=True, default=False)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='courses.enrollment')),
            ],
            options={
                'db_table': 'quiz_attempts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['enrollment', 'passed'], name='quiz_attemp_enrollm_089f55_idx'), models.Index(fields=['enrollment', 'created_at'], name='quiz_attemp_enrollm_945eb5_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.TextField()),
                ('options', models.JSONField(help_text="List of 4 answer strings. Example: ['Paris', 'London', 'Berlin', 'Rome']")),
                ('correct_index', models.PositiveSmallIntegerField(help_text='Zero-based index of the correct answer in the options list (0-3).')),
                ('explanation', models.TextField(blank=True, default='', help_text='Shown to the student after answering. Explains why the answer is correct.')),
                ('position', models.PositiveIntegerField(db_index=True, default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='courses.course')),
            ],
            options={
                'db_table': 'quiz_questions',
                'ordering': ['position'],
                'indexes': [models.Index(fields=['course', 'position'], name='quiz_questi_course__09c9b2_idx')],
            },
        ),
    ]
