# Generated by Django 5.0.6 on 2026-07-14 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0001_initial"),
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="difficulty",
            field=models.CharField(
                blank=True, db_index=True, default="beginner", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="is_certificate_eligible",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="lesson_mapping",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="question_type",
            field=models.CharField(
                blank=True, db_index=True, default="multiple_choice", max_length=40
            ),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="review_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("review_required", "Review Required"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="review_required",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_quiz_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="quizquestion",
            index=models.Index(
                fields=["course", "review_status"], name="quiz_q_course_review_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="quizquestion",
            index=models.Index(
                fields=["course", "is_certificate_eligible"],
                name="quiz_q_course_cert_idx",
            ),
        ),
    ]
