# Generated by Django 5.0.6 on 2026-07-15 17:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0002_quizquestion_difficulty_and_more"),
        ("courses", "0002_courseproject_coursereview_lessonversion_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="category",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="learning_objective",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="reusable_key",
            field=models.SlugField(blank=True, default="", max_length=160),
        ),
        migrations.AddIndex(
            model_name="quizquestion",
            index=models.Index(
                fields=["course", "category"], name="quiz_q_course_category_idx"
            ),
        ),
    ]
