# Generated by Django 5.0.6 on 2026-07-16 06:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessments", "0003_quizquestion_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionReviewDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignment_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("decision", models.CharField(db_index=True, max_length=40)),
                ("section_comments", models.JSONField(blank=True, default=dict)),
                ("required_changes", models.JSONField(blank=True, default=list)),
                ("certificate_eligible", models.BooleanField(default=False)),
                ("marked_reusable", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_decisions",
                        to="assessments.quizquestion",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_review_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "question_review_decisions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["question", "decision"],
                        name="question_re_questio_789d49_idx",
                    ),
                    models.Index(
                        fields=["reviewer", "created_at"],
                        name="question_re_reviewe_e1a86e_idx",
                    ),
                ],
            },
        ),
    ]
