# Generated by Django 5.0.6 on 2026-07-01 14:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_joblisting_job_type'),
        ('tracks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='applications_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='citizenship_requirement',
            field=models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 code if citizenship of a specific country is required.', max_length=2),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, default='GN', help_text='ISO 3166-1 alpha-2 country code. e.g. GN, FR, US', max_length=2),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='is_remote',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='languages_required',
            field=models.JSONField(default=list, help_text="BCP 47 language codes required for this job. e.g. ['fr', 'en']"),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='preferred_skills',
            field=models.JSONField(default=list, help_text='List of preferred but not required skill names.'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='remote_regions',
            field=models.JSONField(default=list, help_text="Regions where remote candidates are accepted. e.g. ['West Africa', 'Europe']"),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='required_skills',
            field=models.JSONField(default=list, help_text="List of required skill names. e.g. ['Python', 'Django']"),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='salary_currency',
            field=models.CharField(choices=[('GNF', 'Guinean Franc'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('XOF', 'CFA Franc BCEAO'), ('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('KES', 'Kenyan Shilling'), ('INR', 'Indian Rupee'), ('CNY', 'Chinese Yuan'), ('BRL', 'Brazilian Real')], default='GNF', max_length=3),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='salary_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='visa_required',
            field=models.BooleanField(default=False, help_text='A visa is required to work in this position.'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='visa_sponsorship',
            field=models.BooleanField(db_index=True, default=False, help_text='The employer sponsors visas for this position.'),
        ),
        migrations.AddField(
            model_name='joblisting',
            name='work_authorization_required',
            field=models.BooleanField(default=False, help_text='Candidates must have work authorization for the job country.'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='apply_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='experience_level',
            field=models.CharField(choices=[('student', 'Student'), ('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('lead', 'Lead / Manager')], db_index=True, default='entry', max_length=20),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['country_code'], name='job_listing_country_eed8a3_idx'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['is_remote'], name='job_listing_is_remo_94126a_idx'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['visa_sponsorship'], name='job_listing_visa_sp_74dc38_idx'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['is_active', 'expires_at'], name='job_listing_is_acti_ac2727_idx'),
        ),
        migrations.AddIndex(
            model_name='joblisting',
            index=models.Index(fields=['experience_level', 'job_type'], name='job_listing_experie_f925ac_idx'),
        ),
    ]
