# Generated by Django 5.0.6 on 2026-07-02 22:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_add_organization_ownership"),
        ("organizations", "0003_recruiter_entitlements_candidate_unlocks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("applied", "Applied"),
                            ("under_review", "Under Review"),
                            ("shortlisted", "Shortlisted"),
                            ("assessment", "Assessment"),
                            ("interview_scheduled", "Interview Scheduled"),
                            ("interview_completed", "Interview Completed"),
                            ("offer_sent", "Offer Sent"),
                            ("offer_accepted", "Offer Accepted"),
                            ("offer_declined", "Offer Declined"),
                            ("rejected", "Rejected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="applied",
                        max_length=30,
                    ),
                ),
                ("cover_letter", models.TextField(blank=True, default="")),
                (
                    "source",
                    models.CharField(blank=True, default="direct", max_length=50),
                ),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_recruiter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hiring_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.joblisting",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "job_applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("phone", "Phone"),
                            ("onsite", "Onsite"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("rescheduled", "Rescheduled"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("scheduled_start", models.DateTimeField(db_index=True)),
                ("scheduled_end", models.DateTimeField(blank=True, null=True)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                (
                    "meeting_link",
                    models.URLField(blank=True, default="", max_length=1000),
                ),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interviews_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="organizations.organization",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="jobs.jobapplication",
                    ),
                ),
            ],
            options={
                "db_table": "interviews",
                "ordering": ["scheduled_start"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationTimeline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("from_stage", models.CharField(blank=True, default="", max_length=30)),
                ("to_stage", models.CharField(blank=True, default="", max_length=30)),
                ("event_type", models.CharField(db_index=True, max_length=50)),
                ("message", models.CharField(blank=True, default="", max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_timeline_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="jobs.jobapplication",
                    ),
                ),
            ],
            options={
                "db_table": "application_timeline",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
                ("is_internal", models.BooleanField(default=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="jobs.jobapplication",
                    ),
                ),
            ],
            options={
                "db_table": "application_notes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_url", models.URLField(max_length=1000)),
                ("file_name", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("is_private", models.BooleanField(default=False)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="jobs.jobapplication",
                    ),
                ),
            ],
            options={
                "db_table": "application_attachments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("activity_type", models.CharField(db_index=True, max_length=50)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="application_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="jobs.jobapplication",
                    ),
                ),
            ],
            options={
                "db_table": "application_activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TalentPool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="talent_pools_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talent_pools",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "talent_pools",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SavedCandidate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("labels", models.JSONField(blank=True, default=list)),
                ("private_notes", models.TextField(blank=True, default="")),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by_recruiters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_candidates",
                        to="organizations.organization",
                    ),
                ),
                (
                    "saved_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_candidates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "talent_pool",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="saved_candidates",
                        to="jobs.talentpool",
                    ),
                ),
            ],
            options={
                "db_table": "saved_candidates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterviewFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rating", models.PositiveSmallIntegerField(default=0)),
                (
                    "recommendation",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("feedback", models.TextField(blank=True, default="")),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interview_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="jobs.interview",
                    ),
                ),
            ],
            options={
                "db_table": "interview_feedback",
                "unique_together": {("interview", "author")},
            },
        ),
        migrations.CreateModel(
            name="InterviewParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("role", models.CharField(default="interviewer", max_length=50)),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="jobs.interview",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "interview_participants",
                "unique_together": {("interview", "user")},
            },
        ),
        migrations.CreateModel(
            name="InterviewScorecard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("criteria", models.JSONField(blank=True, default=dict)),
                (
                    "total_score",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "recommendation",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interview_scorecards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scorecards",
                        to="jobs.interview",
                    ),
                ),
            ],
            options={
                "db_table": "interview_scorecards",
                "unique_together": {("interview", "author")},
            },
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["organization", "stage"], name="job_app_org_stage_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(fields=["job", "stage"], name="job_app_job_stage_idx"),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["candidate", "stage"], name="job_app_candidate_stage_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="jobapplication",
            index=models.Index(
                fields=["organization", "is_archived"], name="job_app_org_archive_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jobapplication",
            unique_together={("job", "candidate")},
        ),
        migrations.AddIndex(
            model_name="interview",
            index=models.Index(
                fields=["organization", "scheduled_start"],
                name="interview_org_start_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="interview",
            index=models.Index(
                fields=["application", "status"], name="interview_app_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="applicationtimeline",
            index=models.Index(
                fields=["application", "created_at"],
                name="app_timeline_app_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="applicationnote",
            index=models.Index(
                fields=["application", "created_at"], name="app_notes_app_created_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="talentpool",
            unique_together={("organization", "name")},
        ),
        migrations.AddIndex(
            model_name="savedcandidate",
            index=models.Index(
                fields=["organization", "candidate"],
                name="saved_candidate_org_user_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="savedcandidate",
            unique_together={("organization", "candidate")},
        ),
    ]
