# Generated by Django 5.0.6 on 2026-07-03 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0003_careerresume_portfolioprojectmedia_resumeanalytics_and_more"),
        ("jobs", "0006_jobalert_savedjobcollection_recentlyviewedjob_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobapplication",
            name="selected_resume",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_applications",
                to="careers.careerresume",
            ),
        ),
    ]
