# Generated by Django 5.0.6 on 2026-07-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_jobapplication_selected_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobalert",
            name="last_matched_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="jobalert",
            name="last_run_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobalert",
            name="total_matched_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
