# Generated by Django 5.0.6 on 2026-07-03 00:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0008_jobalert_last_matched_count_jobalert_last_run_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobApplicationQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question_text", models.CharField(max_length=500)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("short_text", "Short Text"),
                            ("long_text", "Long Text"),
                            ("yes_no", "Yes/No"),
                            ("multiple_choice", "Multiple Choice"),
                            ("number", "Number"),
                            ("url", "URL"),
                        ],
                        default="short_text",
                        max_length=30,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("choices", models.JSONField(blank=True, default=list)),
                ("position", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="application_questions",
                        to="jobs.joblisting",
                    ),
                ),
            ],
            options={
                "db_table": "job_application_questions",
                "ordering": ["position", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="JobApplicationAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("answer", models.JSONField(blank=True, default=dict)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="jobs.jobapplication",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="jobs.jobapplicationquestion",
                    ),
                ),
            ],
            options={
                "db_table": "job_application_answers",
                "ordering": ["question__position", "created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="jobapplicationquestion",
            index=models.Index(
                fields=["job", "is_active"], name="job_question_job_active_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="jobapplicationanswer",
            unique_together={("application", "question")},
        ),
    ]
