# Generated by Django 5.0.6 on 2026-07-15 17:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("instructions", models.TextField(blank=True, default="")),
                ("required_deliverables", models.JSONField(blank=True, default=list)),
                ("rubric", models.JSONField(blank=True, default=list)),
                ("evaluation_criteria", models.JSONField(blank=True, default=list)),
                ("passing_score", models.PositiveSmallIntegerField(default=70)),
                ("reviewer_notes", models.TextField(blank=True, default="")),
                ("example_solution", models.TextField(blank=True, default="")),
                ("resources", models.JSONField(blank=True, default=list)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "approval_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("needs_review", "Needs Review"),
                            ("under_review", "Under Review"),
                            ("changes_requested", "Changes Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "course_projects",
            },
        ),
        migrations.CreateModel(
            name="CourseReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("needs_review", "Needs Review"),
                            ("under_review", "Under Review"),
                            ("changes_requested", "Changes Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("comments", models.TextField(blank=True, default="")),
                ("required_fixes", models.JSONField(blank=True, default=list)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "course_academic_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LessonVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version_number", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=255)),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("text", "Text"),
                            ("quiz", "Quiz"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True, default="")),
                (
                    "summary_of_changes",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "is_published_version",
                    models.BooleanField(db_index=True, default=False),
                ),
            ],
            options={
                "db_table": "lesson_versions",
                "ordering": ["-version_number"],
            },
        ),
        migrations.CreateModel(
            name="ResourceLibraryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("csv", "CSV Dataset"),
                            ("excel", "Excel Workbook"),
                            ("image", "Image"),
                            ("pdf", "PDF"),
                            ("powerpoint", "PowerPoint"),
                            ("notebook", "Python Notebook"),
                            ("sql", "SQL Script"),
                            ("template", "Template"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=30,
                    ),
                ),
                ("file_url", models.URLField(blank=True, default="", max_length=1000)),
                (
                    "storage_key",
                    models.CharField(blank=True, default="", max_length=1000),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("course", "Course"),
                            ("public", "Public"),
                        ],
                        db_index=True,
                        default="private",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "resource_library_items",
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="draft_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="lesson",
            name="published_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lesson",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("needs_review", "Needs Review"),
                    ("under_review", "Under Review"),
                    ("changes_requested", "Changes Requested"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="draft",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(
                fields=["course", "review_status"], name="lesson_course_review_idx"
            ),
        ),
        migrations.AddField(
            model_name="courseproject",
            name="course",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="courseproject",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="coursereview",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_reviews",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="coursereview",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="academic_course_reviews_completed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="coursereview",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="academic_course_reviews_submitted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lessonversion",
            name="editor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_versions_edited",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lessonversion",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="courses.lesson",
            ),
        ),
        migrations.AddField(
            model_name="resourcelibraryitem",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resources",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="resourcelibraryitem",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="course_resources",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="courseproject",
            index=models.Index(
                fields=["approval_state"], name="course_proj_approva_73a0ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="coursereview",
            index=models.Index(
                fields=["course", "status"], name="course_academic_review_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonversion",
            index=models.Index(
                fields=["lesson", "version_number"],
                name="lesson_vers_lesson__3b2cef_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="lessonversion",
            unique_together={("lesson", "version_number")},
        ),
        migrations.AddIndex(
            model_name="resourcelibraryitem",
            index=models.Index(
                fields=["owner", "resource_type"], name="resource_li_owner_i_2358cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resourcelibraryitem",
            index=models.Index(
                fields=["course", "visibility"], name="resource_li_course__ff8d45_idx"
            ),
        ),
    ]
