# Generated by Django 5.0.6 on 2026-07-16 06:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_courseproject_coursereview_lessonversion_and_more"),
        ("organizations", "0007_dataexportjob_file_deleted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicReviewerProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reviewer_role",
                    models.CharField(
                        choices=[
                            (
                                "platform_academic_reviewer",
                                "Platform Academic Reviewer",
                            ),
                            (
                                "organization_academic_reviewer",
                                "Organization Academic Reviewer",
                            ),
                            ("course_reviewer", "Course Reviewer"),
                            ("subject_reviewer", "Subject Reviewer"),
                            ("lead_reviewer", "Lead Reviewer"),
                        ],
                        db_index=True,
                        default="course_reviewer",
                        max_length=60,
                    ),
                ),
                ("subject_tags", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "db_table": "academic_reviewer_profiles",
            },
        ),
        migrations.CreateModel(
            name="CourseProjectReviewDecision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("approve_minor_edits", "Approve With Minor Edits"),
                            ("request_changes", "Request Changes"),
                            ("reject", "Reject"),
                            ("escalate", "Escalate"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("project_version", models.PositiveIntegerField(default=1)),
                ("review_sections", models.JSONField(blank=True, default=dict)),
                ("required_changes", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "course_project_review_decisions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LessonStructuredReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approve", "Approve"),
                            ("approve_minor_edits", "Approve With Minor Edits"),
                            ("request_changes", "Request Changes"),
                            ("reject", "Reject"),
                            ("escalate", "Escalate"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("section_comments", models.JSONField(blank=True, default=dict)),
                ("required_changes", models.JSONField(blank=True, default=list)),
                ("instructor_response", models.TextField(blank=True, default="")),
                ("addressed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "lesson_structured_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("course", "Course"),
                            ("lesson", "Lesson"),
                            ("assessment", "Assessment"),
                            ("project", "Final Project"),
                            ("resource", "Resource"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("target_id", models.UUIDField(db_index=True)),
                (
                    "subject",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        db_index=True,
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("needs_review", "Needs Review"),
                            ("under_review", "Under Review"),
                            ("changes_requested", "Changes Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="needs_review",
                        max_length=30,
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("reassignment_history", models.JSONField(blank=True, default=list)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "academic_review_assignments",
                "ordering": ["due_date", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="resourcelibraryitem",
            name="checksum",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=128
            ),
        ),
        migrations.AddField(
            model_name="resourcelibraryitem",
            name="content_type",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="resourcelibraryitem",
            name="download_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resourcelibraryitem",
            name="file_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="resourcelibraryitem",
            name="file_size_bytes",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="resourcelibraryitem",
            name="malware_scan_status",
            field=models.CharField(blank=True, default="pending", max_length=40),
        ),
        migrations.AddField(
            model_name="resourcelibraryitem",
            name="review_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="resourcelibraryitem",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("needs_review", "Needs Review"),
                    ("under_review", "Under Review"),
                    ("changes_requested", "Changes Requested"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="draft",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="resourcelibraryitem",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resourcelibraryitem",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_course_resources",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="resourcelibraryitem",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("csv", "CSV Dataset"),
                    ("excel", "Excel Workbook"),
                    ("image", "Image"),
                    ("pdf", "PDF"),
                    ("powerpoint", "PowerPoint"),
                    ("docx", "Word Document"),
                    ("notebook", "Python Notebook"),
                    ("sql", "SQL Script"),
                    ("txt", "Text"),
                    ("zip", "ZIP Archive"),
                    ("template", "Template"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="resourcelibraryitem",
            index=models.Index(
                fields=["course", "review_status"],
                name="resource_li_course__6af8cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resourcelibraryitem",
            index=models.Index(
                fields=["checksum"], name="resource_li_checksu_c2ce4d_idx"
            ),
        ),
        migrations.AddField(
            model_name="academicreviewerprofile",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_reviewers",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="academicreviewerprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_reviewer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="courseprojectreviewdecision",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_decisions",
                to="courses.courseproject",
            ),
        ),
        migrations.AddField(
            model_name="courseprojectreviewdecision",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="course_project_review_decisions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lessonstructuredreview",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="structured_reviews",
                to="courses.lesson",
            ),
        ),
        migrations.AddField(
            model_name="lessonstructuredreview",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lesson_structured_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reviewassignment",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="academic_review_assignments_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reviewassignment",
            name="assigned_reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="academic_review_assignments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reviewassignment",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_assignments",
                to="courses.course",
            ),
        ),
        migrations.AddField(
            model_name="reviewassignment",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_assignments",
                to="courses.lesson",
            ),
        ),
        migrations.AddField(
            model_name="reviewassignment",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="academic_review_assignments",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="lessonstructuredreview",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lesson_reviews",
                to="courses.reviewassignment",
            ),
        ),
        migrations.AddField(
            model_name="courseprojectreviewdecision",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="project_reviews",
                to="courses.reviewassignment",
            ),
        ),
        migrations.AddIndex(
            model_name="academicreviewerprofile",
            index=models.Index(
                fields=["reviewer_role", "is_active"],
                name="academic_re_reviewe_927b13_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="academicreviewerprofile",
            index=models.Index(
                fields=["organization", "is_active"],
                name="academic_re_organiz_b9b63d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewassignment",
            index=models.Index(
                fields=["assigned_reviewer", "review_status"],
                name="academic_re_assigne_c1dbbe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewassignment",
            index=models.Index(
                fields=["target_type", "target_id"],
                name="academic_re_target__4c1a2c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewassignment",
            index=models.Index(
                fields=["course", "review_status"],
                name="academic_re_course__56e3c9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewassignment",
            index=models.Index(
                fields=["priority", "due_date"], name="academic_re_priorit_4a2d7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonstructuredreview",
            index=models.Index(
                fields=["lesson", "decision"], name="lesson_stru_lesson__c2e2b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lessonstructuredreview",
            index=models.Index(
                fields=["reviewer", "created_at"], name="lesson_stru_reviewe_efc606_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="courseprojectreviewdecision",
            index=models.Index(
                fields=["project", "project_version"],
                name="course_proj_project_4fe2a6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="courseprojectreviewdecision",
            index=models.Index(
                fields=["reviewer", "created_at"], name="course_proj_reviewe_8a37a0_idx"
            ),
        ),
    ]
