# Generated by Django 5.0.6 on 2026-07-16 13:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "courses",
            "0003_academicreviewerprofile_courseprojectreviewdecision_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicOverrideLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("target_type", models.CharField(db_index=True, max_length=60)),
                ("target_id", models.UUIDField(db_index=True)),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("reassignment", "Reviewer reassignment"),
                            (
                                "emergency_publication_rollback",
                                "Emergency publication rollback",
                            ),
                            ("reviewer_absence", "Reviewer absence"),
                            ("incorrect_stuck_state", "Incorrect stuck state"),
                            ("security_issue", "Security issue"),
                            ("legal_issue", "Legal issue"),
                        ],
                        db_index=True,
                        max_length=60,
                    ),
                ),
                ("reason", models.TextField()),
                ("previous_state", models.JSONField(blank=True, default=dict)),
                ("new_state", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "academic_override_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="academicreviewerprofile",
            name="automatic_assignment_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="academicreviewerprofile",
            name="max_active_assignments",
            field=models.PositiveSmallIntegerField(default=25),
        ),
        migrations.AddField(
            model_name="resourcelibraryitem",
            name="malware_scan_result",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="resourcelibraryitem",
            name="malware_scanned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resourcelibraryitem",
            name="malware_scanner",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="reviewassignment",
            name="escalated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewassignment",
            name="escalated_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="academic_review_escalations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reviewassignment",
            name="escalation_level",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="reviewassignment",
            name="escalation_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddIndex(
            model_name="resourcelibraryitem",
            index=models.Index(
                fields=["malware_scan_status"], name="resource_li_malware_664886_idx"
            ),
        ),
        migrations.AddField(
            model_name="academicoverridelog",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="academic_overrides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="academicoverridelog",
            index=models.Index(
                fields=["target_type", "target_id"],
                name="academic_ov_target__32c6cd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="academicoverridelog",
            index=models.Index(
                fields=["reason_code", "created_at"],
                name="academic_ov_reason__2838bd_idx",
            ),
        ),
    ]
