from django.conf import settings
from django.db import models
from django.utils import timezone
from common.models import BaseModel


class DocumentType(models.TextChoices):
    NATIONAL_ID = "national_id", "National ID Card"
    PASSPORT = "passport", "Passport"
    DRIVERS_LICENSE = "drivers_license", "Driver's License"
    RESIDENCE_PERMIT = "residence_permit", "Residence Permit"
    GOVERNMENT_ID_OTHER = "government_id_other", "Other Government ID"
    BUSINESS_REGISTRATION = "business_registration", "Business Registration Certificate"
    TAX_REGISTRATION = "tax_registration", "Tax Registration Document"
    BUSINESS_LICENSE = "business_license", "Business License"
    COMPANY_DOC_OTHER = "company_doc_other", "Other Company Document"
    TEACHING_DEMO = "teaching_demo", "Teaching Demo Video"


class VerificationPriority(models.TextChoices):
    HIGH = "high", "High Priority"
    NORMAL = "normal", "Normal"
    LOW = "low", "Low Priority"


class VerificationRequestStatus(models.TextChoices):
    SUBMITTED = "submitted", "Submitted"
    UNDER_REVIEW = "under_review", "Under Review"
    APPROVED = "approved", "Approved"
    REJECTED = "rejected", "Rejected"
    MORE_INFO_REQUIRED = "more_info_required", "More Information Required"


class SubjectType(models.TextChoices):
    INSTRUCTOR = "instructor", "Instructor"
    RECRUITER = "recruiter", "Recruiter"
    ORGANIZATION = "organization", "Organization"


class VerificationActionType(models.TextChoices):
    SUBMITTED = "submitted", "Submitted for Review"
    ASSIGNED = "assigned", "Assigned to Reviewer"
    APPROVED = "approved", "Approved"
    REJECTED = "rejected", "Rejected"
    SUSPENDED = "suspended", "Suspended"
    REINSTATED = "reinstated", "Reinstated"
    MORE_INFO_REQUESTED = "more_info_requested", "More Information Requested"
    PRIORITY_CHANGED = "priority_changed", "Priority Changed"
    DOCUMENT_UPLOADED = "document_uploaded", "Document Uploaded"
    DOCUMENT_DELETED = "document_deleted", "Document Deleted"
    SIGNED_URL_GENERATED = "signed_url_generated", "Document Accessed via Signed URL"


class IdentityVerificationDocument(BaseModel):
    # Private document storage for identity and organization verification.
    # S3 keys are never exposed publicly.
    # Access is always through short-lived signed URLs generated by staff only.

    owner_type = models.CharField(
        max_length=30,
        choices=SubjectType.choices,
        db_index=True,
    )
    owner_id = models.UUIDField(db_index=True)
    document_type = models.CharField(
        max_length=30,
        choices=DocumentType.choices,
    )

    # S3 storage - keys never returned in API responses
    s3_bucket = models.CharField(max_length=100)
    s3_key = models.CharField(max_length=500)

    # Display metadata for staff review interface
    file_name = models.CharField(max_length=255)
    file_size = models.PositiveIntegerField(help_text="File size in bytes.")
    mime_type = models.CharField(max_length=100)

    is_encrypted = models.BooleanField(default=True)
    uploaded_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="uploaded_documents",
    )

    # Document expiry for documents that require periodic re-verification
    expires_at = models.DateField(null=True, blank=True)
    verified_until = models.DateField(null=True, blank=True)

    # Soft delete: superseded documents are deactivated, not deleted
    is_active = models.BooleanField(default=True, db_index=True)

    # Staff notes on this specific document
    staff_notes = models.TextField(blank=True, default="")

    class Meta:
        db_table = "identity_verification_documents"
        indexes = [
            models.Index(fields=["owner_type", "owner_id"]),
            models.Index(fields=["owner_type", "owner_id", "is_active"]),
            models.Index(fields=["document_type"]),
        ]

    def __str__(self):
        return f"{self.document_type} for {self.owner_type}:{self.owner_id}"


class VerificationRequest(BaseModel):
    # Tracks a single verification submission lifecycle.
    # Three note fields are kept separate to prevent mixing
    # applicant communication with internal reviewer notes.

    subject_type = models.CharField(
        max_length=30,
        choices=SubjectType.choices,
        db_index=True,
    )
    subject_id = models.UUIDField(db_index=True)
    submitted_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="verification_requests_submitted",
    )
    status = models.CharField(
        max_length=30,
        choices=VerificationRequestStatus.choices,
        default=VerificationRequestStatus.SUBMITTED,
        db_index=True,
    )
    priority = models.CharField(
        max_length=20,
        choices=VerificationPriority.choices,
        default=VerificationPriority.NORMAL,
        db_index=True,
    )
    priority_reason = models.CharField(
        max_length=100,
        blank=True,
        default="",
        help_text="e.g. paid_instructor, enterprise_company, university",
    )
    assigned_to = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="verification_requests_assigned",
    )

    # Three separate note fields to prevent mixing communication channels
    applicant_notes = models.TextField(
        blank=True,
        default="",
        help_text="Notes submitted by the applicant during submission.",
    )
    reviewer_notes = models.TextField(
        blank=True,
        default="",
        help_text="Notes written by the reviewer for the applicant to read.",
    )
    internal_notes = models.TextField(
        blank=True,
        default="",
        help_text="Internal administrative notes. Never shown to applicant.",
    )

    submitted_at = models.DateTimeField(auto_now_add=True)
    reviewed_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = "verification_requests"
        ordering = ["-priority", "submitted_at"]
        indexes = [
            models.Index(fields=["subject_type", "subject_id"]),
            models.Index(fields=["status", "priority"]),
            models.Index(fields=["assigned_to", "status"]),
        ]

    def __str__(self):
        return f"VerificationRequest({self.subject_type}:{self.subject_id} - {self.status})"


class VerificationAction(BaseModel):
    # Append-only audit log for all verification actions.
    # No row is ever updated or deleted.
    # Records full request context for traceability.

    actor = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="verification_actions",
    )
    target_type = models.CharField(max_length=30, choices=SubjectType.choices, db_index=True)
    target_id = models.UUIDField(db_index=True)
    action = models.CharField(
        max_length=30,
        choices=VerificationActionType.choices,
        db_index=True,
    )
    previous_status = models.CharField(max_length=30, blank=True, default="")
    new_status = models.CharField(max_length=30, blank=True, default="")
    reason = models.TextField(blank=True, default="")
    notes = models.TextField(blank=True, default="")

    # Full request context for security traceability
    ip_address = models.CharField(max_length=45, blank=True, default="")
    device = models.CharField(max_length=200, blank=True, default="")
    browser = models.CharField(max_length=200, blank=True, default="")
    country = models.CharField(max_length=100, blank=True, default="")
    city = models.CharField(max_length=100, blank=True, default="")

    performed_at = models.DateTimeField(default=timezone.now)

    class Meta:
        db_table = "verification_actions"
        get_latest_by = ["performed_at", "created_at"]
        ordering = ["-performed_at", "-created_at"]
        indexes = [
            models.Index(fields=["target_type", "target_id"]),
            models.Index(fields=["actor", "performed_at"]),
            models.Index(fields=["action", "performed_at"]),
        ]

    def save(self, *args, **kwargs):
        # Enforce append-only: prevent updates to existing rows
        if not self._state.adding:
            raise ValueError("VerificationAction records are append-only and cannot be updated.")
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.action} on {self.target_type}:{self.target_id} by {self.actor_id}"
