# Generated by Django 5.0.6 on 2026-07-02 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0002_seed_data"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="exchangerate",
            new_name="geo_exchang_from_cu_64e2b5_idx",
            old_name="geo_exchan_from_cu_idx",
        ),
        migrations.AlterField(
            model_name="countrysettings",
            name="email_provider",
            field=models.CharField(
                default="ses", help_text="ses, sendgrid, mailgun", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="countrysettings",
            name="number_format",
            field=models.CharField(
                default="space_comma",
                help_text="space_comma: 1 000,00 | comma_dot: 1,000.00",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="countrysettings",
            name="payment_currencies",
            field=models.JSONField(
                default=list,
                help_text='Currencies accepted for payment: ["GNF", "USD"]',
            ),
        ),
        migrations.AlterField(
            model_name="countrysettings",
            name="payment_providers",
            field=models.JSONField(
                default=list,
                help_text='Ordered list of provider keys: ["orange_money", "stripe"]',
            ),
        ),
        migrations.AlterField(
            model_name="countrysettings",
            name="push_provider",
            field=models.CharField(default="fcm", help_text="fcm, apns", max_length=50),
        ),
        migrations.AlterField(
            model_name="countrysettings",
            name="sms_provider",
            field=models.CharField(
                blank=True,
                default="",
                help_text="twilio, orange_api, mtn_api",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="countrysettings",
            name="supported_languages",
            field=models.JSONField(
                default=list,
                help_text='Languages available in this country: ["fr", "en"]',
            ),
        ),
        migrations.AlterField(
            model_name="countrysettings",
            name="tax_label",
            field=models.CharField(
                default="VAT",
                help_text="Label shown to user: VAT, GST, TVA, etc.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="countrysettings",
            name="vat_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=0.0,
                help_text="e.g. 0.18 for 18 percent VAT",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="is_content_language",
            field=models.BooleanField(
                default=False, help_text="Available for course content translation."
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="is_ui_language",
            field=models.BooleanField(
                default=False, help_text="Available as a platform UI language."
            ),
        ),
    ]
