# Generated by Django 5.0.6 on 2026-07-03 22:56

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        ("organizations", "0007_dataexportjob_file_deleted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIProvider",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("google_gemini", "Google Gemini"),
                            ("azure_openai", "Azure OpenAI"),
                            ("local", "Local Model"),
                            ("mock", "Mock Provider"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                ("priority", models.PositiveSmallIntegerField(default=100)),
                ("timeout_seconds", models.PositiveSmallIntegerField(default=30)),
                ("max_retries", models.PositiveSmallIntegerField(default=1)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "ai_providers",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="AIConversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("resume_review", "Resume Review"),
                            ("portfolio_review", "Portfolio Review"),
                            ("career_advice", "Career Advice"),
                            ("learning_recommendations", "Learning Recommendations"),
                            ("job_matching", "Job Matching"),
                            ("course_tutor", "Course Tutor"),
                            ("interview_coach", "Interview Coach"),
                            ("skill_gap_analysis", "Skill Gap Analysis"),
                            ("application_review", "Application Review"),
                            ("cover_letter", "Cover Letter"),
                        ],
                        db_index=True,
                        default="chat",
                        max_length=50,
                    ),
                ),
                ("locale", models.CharField(default="en", max_length=20)),
                ("is_archived", models.BooleanField(db_index=True, default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_conversations",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_conversations",
            },
        ),
        migrations.CreateModel(
            name="AIJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("resume_review", "Resume Review"),
                            ("portfolio_review", "Portfolio Review"),
                            ("career_advice", "Career Advice"),
                            ("learning_recommendations", "Learning Recommendations"),
                            ("job_matching", "Job Matching"),
                            ("course_tutor", "Course Tutor"),
                            ("interview_coach", "Interview Coach"),
                            ("skill_gap_analysis", "Skill Gap Analysis"),
                            ("application_review", "Application Review"),
                            ("cover_letter", "Cover Letter"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("progress_percentage", models.PositiveSmallIntegerField(default=0)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("input_payload", models.JSONField(blank=True, default=dict)),
                ("failure_reason", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_jobs",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_jobs",
            },
        ),
        migrations.CreateModel(
            name="AIPromptTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(db_index=True, max_length=100)),
                ("name", models.CharField(max_length=160)),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("resume_review", "Resume Review"),
                            ("portfolio_review", "Portfolio Review"),
                            ("career_advice", "Career Advice"),
                            ("learning_recommendations", "Learning Recommendations"),
                            ("job_matching", "Job Matching"),
                            ("course_tutor", "Course Tutor"),
                            ("interview_coach", "Interview Coach"),
                            ("skill_gap_analysis", "Skill Gap Analysis"),
                            ("application_review", "Application Review"),
                            ("cover_letter", "Cover Letter"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "locale",
                    models.CharField(db_index=True, default="en", max_length=20),
                ),
                ("variant", models.CharField(blank=True, default="", max_length=50)),
                ("system_prompt", models.TextField(blank=True, default="")),
                ("user_prompt", models.TextField()),
                ("variables", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "ai_prompt_templates",
                "indexes": [
                    models.Index(
                        fields=["key", "is_active", "locale"],
                        name="ai_prompt_key_locale_idx",
                    )
                ],
                "unique_together": {("key", "version", "locale", "variant")},
            },
        ),
        migrations.CreateModel(
            name="AIModelConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_name", models.CharField(max_length=120)),
                (
                    "display_name",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                ("max_tokens", models.PositiveIntegerField(default=1000)),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.30"), max_digits=4
                    ),
                ),
                (
                    "input_token_cost",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0E-8"), max_digits=12
                    ),
                ),
                (
                    "output_token_cost",
                    models.DecimalField(
                        decimal_places=8, default=Decimal("0E-8"), max_digits=12
                    ),
                ),
                ("timeout_seconds", models.PositiveSmallIntegerField(default=30)),
                ("max_retries", models.PositiveSmallIntegerField(default=1)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_configurations",
                        to="ai_platform.aiprovider",
                    ),
                ),
            ],
            options={
                "db_table": "ai_model_configurations",
            },
        ),
        migrations.CreateModel(
            name="AIRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("resume_review", "Resume Review"),
                            ("portfolio_review", "Portfolio Review"),
                            ("career_advice", "Career Advice"),
                            ("learning_recommendations", "Learning Recommendations"),
                            ("job_matching", "Job Matching"),
                            ("course_tutor", "Course Tutor"),
                            ("interview_coach", "Interview Coach"),
                            ("skill_gap_analysis", "Skill Gap Analysis"),
                            ("application_review", "Application Review"),
                            ("cover_letter", "Cover Letter"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        db_index=True, default="generate_text", max_length=50
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("blocked", "Blocked"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("input_text", models.TextField(blank=True, default="")),
                ("redacted_input", models.TextField(blank=True, default="")),
                ("rendered_prompt", models.JSONField(blank=True, default=dict)),
                ("safety_flags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="ai_platform.aiconversation",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_requests",
                        to="courses.course",
                    ),
                ),
                (
                    "model_configuration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="ai_platform.aimodelconfiguration",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_requests",
                        to="organizations.organization",
                    ),
                ),
                (
                    "prompt_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="ai_platform.aiprompttemplate",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requests",
                        to="ai_platform.aiprovider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_requests",
            },
        ),
        migrations.CreateModel(
            name="AIResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("output_text", models.TextField(blank=True, default="")),
                ("raw_response", models.JSONField(blank=True, default=dict)),
                (
                    "finish_reason",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("safety_flags", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response",
                        to="ai_platform.airequest",
                    ),
                ),
            ],
            options={
                "db_table": "ai_responses",
            },
        ),
        migrations.CreateModel(
            name="AIResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("result_type", models.CharField(default="text", max_length=80)),
                ("content", models.JSONField(blank=True, default=dict)),
                ("summary", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "job",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="ai_platform.aijob",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="results",
                        to="ai_platform.airequest",
                    ),
                ),
            ],
            options={
                "db_table": "ai_results",
            },
        ),
        migrations.CreateModel(
            name="AITokenUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=12
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="token_usages",
                        to="ai_platform.aiprovider",
                    ),
                ),
                (
                    "request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="token_usage",
                        to="ai_platform.airequest",
                    ),
                ),
            ],
            options={
                "db_table": "ai_token_usage",
            },
        ),
        migrations.CreateModel(
            name="AIUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("resume_review", "Resume Review"),
                            ("portfolio_review", "Portfolio Review"),
                            ("career_advice", "Career Advice"),
                            ("learning_recommendations", "Learning Recommendations"),
                            ("job_matching", "Job Matching"),
                            ("course_tutor", "Course Tutor"),
                            ("interview_coach", "Interview Coach"),
                            ("skill_gap_analysis", "Skill Gap Analysis"),
                            ("application_review", "Application Review"),
                            ("cover_letter", "Cover Letter"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("period_date", models.DateField(db_index=True)),
                ("request_count", models.PositiveIntegerField(default=0)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=12
                    ),
                ),
                ("latency_ms_total", models.PositiveIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_usage_records",
                        to="courses.course",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_records",
                        to="organizations.organization",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_records",
                        to="ai_platform.aiprovider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_usage_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_usage",
            },
        ),
        migrations.CreateModel(
            name="AIBudgetPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("global", "Global"),
                            ("organization", "Organization"),
                            ("user", "User"),
                            ("feature", "Feature"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("chat", "Chat"),
                            ("resume_review", "Resume Review"),
                            ("portfolio_review", "Portfolio Review"),
                            ("career_advice", "Career Advice"),
                            ("learning_recommendations", "Learning Recommendations"),
                            ("job_matching", "Job Matching"),
                            ("course_tutor", "Course Tutor"),
                            ("interview_coach", "Interview Coach"),
                            ("skill_gap_analysis", "Skill Gap Analysis"),
                            ("application_review", "Application Review"),
                            ("cover_letter", "Cover Letter"),
                        ],
                        db_index=True,
                        default="",
                        max_length=50,
                    ),
                ),
                (
                    "daily_request_limit",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "monthly_request_limit",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "daily_token_limit",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "monthly_token_limit",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "monthly_cost_limit",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_budget_policies",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_budget_policies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_budget_policies",
                "indexes": [
                    models.Index(
                        fields=["scope", "feature", "is_active"],
                        name="ai_budget_scope_feature_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="aiconversation",
            index=models.Index(
                fields=["user", "feature", "created_at"],
                name="ai_conv_user_feature_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiconversation",
            index=models.Index(
                fields=["organization", "feature"], name="ai_conv_org_feature_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aijob",
            index=models.Index(
                fields=["organization", "feature", "status"],
                name="ai_job_org_feature_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aimodelconfiguration",
            index=models.Index(
                fields=["provider", "is_default"], name="ai_model_provider_default_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aimodelconfiguration",
            unique_together={("provider", "model_name")},
        ),
        migrations.AddIndex(
            model_name="airequest",
            index=models.Index(
                fields=["user", "feature", "created_at"], name="ai_req_user_feature_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airequest",
            index=models.Index(
                fields=["organization", "feature"], name="ai_req_org_feature_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airequest",
            index=models.Index(
                fields=["provider", "status"], name="ai_req_provider_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aitokenusage",
            index=models.Index(
                fields=["provider", "model_name"], name="ai_token_provider_model_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiusage",
            index=models.Index(
                fields=["organization", "feature", "period_date"],
                name="ai_usage_org_feature_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiusage",
            index=models.Index(
                fields=["user", "feature", "period_date"],
                name="ai_usage_user_feature_date_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aiusage",
            unique_together={
                (
                    "user",
                    "organization",
                    "course",
                    "feature",
                    "provider",
                    "model_name",
                    "period_date",
                )
            },
        ),
    ]
