# Generated by Django 5.0.6 on 2026-07-04 00:48

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_platform", "0001_initial"),
        ("organizations", "0007_dataexportjob_file_deleted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIEvaluationDataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160, unique=True)),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("resume_review", "Resume Review"),
                            ("portfolio_review", "Portfolio Review"),
                            ("career_advice", "Career Advice"),
                            ("learning_recommendations", "Learning Recommendations"),
                            ("job_matching", "Job Matching"),
                            ("course_tutor", "Course Tutor"),
                            ("interview_coach", "Interview Coach"),
                            ("skill_gap_analysis", "Skill Gap Analysis"),
                            ("application_review", "Application Review"),
                            ("cover_letter", "Cover Letter"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("examples", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "ai_evaluation_datasets",
            },
        ),
        migrations.AddField(
            model_name="aibudgetpolicy",
            name="alert_threshold_percent",
            field=models.PositiveSmallIntegerField(default=80),
        ),
        migrations.AddField(
            model_name="aibudgetpolicy",
            name="last_alert_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aiprovider",
            name="health_status",
            field=models.CharField(db_index=True, default="unknown", max_length=30),
        ),
        migrations.AddField(
            model_name="aiprovider",
            name="last_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="aiprovider",
            name="last_health_check_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="airequest",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aitokenusage",
            name="actual_cost",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="aitokenusage",
            name="cost_variance",
            field=models.DecimalField(
                decimal_places=6, default=Decimal("0.000000"), max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="aitokenusage",
            name="provider_reported_input_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aitokenusage",
            name="provider_reported_output_tokens",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="AIEvaluationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "average_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("average_latency_ms", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=12
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_evaluation_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="ai_platform.aievaluationdataset",
                    ),
                ),
                (
                    "model_configuration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluation_runs",
                        to="ai_platform.aimodelconfiguration",
                    ),
                ),
                (
                    "prompt_template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluation_runs",
                        to="ai_platform.aiprompttemplate",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluation_runs",
                        to="ai_platform.aiprovider",
                    ),
                ),
            ],
            options={
                "db_table": "ai_evaluation_runs",
            },
        ),
        migrations.CreateModel(
            name="AIEvaluationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("input_text", models.TextField()),
                ("expected_output", models.TextField(blank=True, default="")),
                ("actual_output", models.TextField(blank=True, default="")),
                (
                    "score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=12
                    ),
                ),
                ("hallucination_notes", models.TextField(blank=True, default="")),
                (
                    "manual_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="ai_platform.aievaluationrun",
                    ),
                ),
            ],
            options={
                "db_table": "ai_evaluation_results",
            },
        ),
        migrations.CreateModel(
            name="VectorCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "embedding_model",
                    models.CharField(default="mock-embedding", max_length=120),
                ),
                ("dimensions", models.PositiveIntegerField(default=16)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vector_collections",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "ai_vector_collections",
            },
        ),
        migrations.CreateModel(
            name="AIFeatureFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("resume_review", "Resume Review"),
                            ("portfolio_review", "Portfolio Review"),
                            ("career_advice", "Career Advice"),
                            ("learning_recommendations", "Learning Recommendations"),
                            ("job_matching", "Job Matching"),
                            ("course_tutor", "Course Tutor"),
                            ("interview_coach", "Interview Coach"),
                            ("skill_gap_analysis", "Skill Gap Analysis"),
                            ("application_review", "Application Review"),
                            ("cover_letter", "Cover Letter"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("is_enabled", models.BooleanField(db_index=True, default=True)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_feature_flags",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_feature_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_feature_flags",
                "indexes": [
                    models.Index(
                        fields=["feature", "is_enabled"],
                        name="ai_flag_feature_enabled_idx",
                    )
                ],
                "unique_together": {("feature", "organization", "user")},
            },
        ),
        migrations.CreateModel(
            name="AIModerationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[("input", "Input"), ("output", "Output")],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("is_allowed", models.BooleanField(db_index=True, default=True)),
                (
                    "severity",
                    models.CharField(db_index=True, default="info", max_length=20),
                ),
                ("categories", models.JSONField(blank=True, default=list)),
                ("pii_findings", models.JSONField(blank=True, default=list)),
                ("injection_findings", models.JSONField(blank=True, default=list)),
                ("raw_result", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_moderation_results",
                        to="organizations.organization",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_results",
                        to="ai_platform.aiprovider",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_results",
                        to="ai_platform.airequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_moderation_results",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_moderation_results",
                "indexes": [
                    models.Index(
                        fields=["organization", "stage", "is_allowed"],
                        name="ai_mod_org_stage_allowed_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="VectorDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document_type", models.CharField(db_index=True, max_length=40)),
                ("object_id", models.CharField(db_index=True, max_length=100)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("content", models.TextField()),
                ("redacted_content", models.TextField(blank=True, default="")),
                ("embedding", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="ai_platform.vectorcollection",
                    ),
                ),
            ],
            options={
                "db_table": "ai_vector_documents",
                "indexes": [
                    models.Index(
                        fields=["collection", "document_type"],
                        name="ai_vec_collection_type_idx",
                    )
                ],
                "unique_together": {("collection", "document_type", "object_id")},
            },
        ),
    ]
