# Generated by Django 5.0.6 on 2026-07-07 21:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_platform", "0002_aievaluationdataset_and_more"),
        ("organizations", "0007_dataexportjob_file_deleted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIInterviewSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("behavioral", "Behavioral"),
                            ("technical", "Technical"),
                            ("system_design", "System Design"),
                            ("coding", "Coding"),
                            ("hr", "HR"),
                            ("leadership", "Leadership"),
                            ("language_interview", "Language Interview"),
                            ("custom", "Custom Interview"),
                        ],
                        db_index=True,
                        default="behavioral",
                        max_length=30,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        db_index=True,
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("job_title", models.CharField(blank=True, default="", max_length=160)),
                ("industry", models.CharField(blank=True, default="", max_length=120)),
                (
                    "experience_level",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "company_type",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("language", models.CharField(default="English", max_length=40)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("resume_context", models.TextField(blank=True, default="")),
                ("portfolio_context", models.TextField(blank=True, default="")),
                ("history", models.JSONField(blank=True, default=list)),
                ("summary", models.TextField(blank=True, default="")),
                ("feedback", models.JSONField(blank=True, default=dict)),
                ("overall_score", models.PositiveSmallIntegerField(default=0)),
                ("confidence_trend", models.JSONField(blank=True, default=list)),
                ("communication_trend", models.JSONField(blank=True, default=list)),
                ("technical_trend", models.JSONField(blank=True, default=list)),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=12
                    ),
                ),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("total_tokens", models.PositiveIntegerField(default=0)),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "model_configuration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interview_sessions",
                        to="ai_platform.aimodelconfiguration",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_interview_sessions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interview_sessions",
                        to="ai_platform.aiprovider",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_interview_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_interview_sessions",
            },
        ),
        migrations.CreateModel(
            name="AIInterviewQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("question_text", models.TextField()),
                (
                    "skill_area",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "ai_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interview_questions",
                        to="ai_platform.airequest",
                    ),
                ),
                (
                    "ai_response",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interview_questions",
                        to="ai_platform.airesponse",
                    ),
                ),
                (
                    "follow_up_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="follow_ups",
                        to="ai_platform.aiinterviewquestion",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="ai_platform.aiinterviewsession",
                    ),
                ),
            ],
            options={
                "db_table": "ai_interview_questions",
                "ordering": ["sequence", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIInterviewAnswerEvaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("answer_text", models.TextField()),
                ("clarity", models.PositiveSmallIntegerField(default=0)),
                ("confidence", models.PositiveSmallIntegerField(default=0)),
                ("technical_quality", models.PositiveSmallIntegerField(default=0)),
                ("communication", models.PositiveSmallIntegerField(default=0)),
                ("structure", models.PositiveSmallIntegerField(default=0)),
                ("problem_solving", models.PositiveSmallIntegerField(default=0)),
                ("accuracy", models.PositiveSmallIntegerField(default=0)),
                ("professionalism", models.PositiveSmallIntegerField(default=0)),
                ("overall_score", models.PositiveSmallIntegerField(default=0)),
                ("strengths", models.JSONField(blank=True, default=list)),
                ("weaknesses", models.JSONField(blank=True, default=list)),
                ("better_answer", models.TextField(blank=True, default="")),
                ("tips", models.JSONField(blank=True, default=list)),
                (
                    "next_practice_goal",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "ai_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interview_evaluations",
                        to="ai_platform.airequest",
                    ),
                ),
                (
                    "ai_response",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interview_evaluations",
                        to="ai_platform.airesponse",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="ai_platform.aiinterviewquestion",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="ai_platform.aiinterviewsession",
                    ),
                ),
            ],
            options={
                "db_table": "ai_interview_answer_evaluations",
            },
        ),
        migrations.CreateModel(
            name="AIInterviewTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("behavioral", "Behavioral"),
                            ("technical", "Technical"),
                            ("system_design", "System Design"),
                            ("coding", "Coding"),
                            ("hr", "HR"),
                            ("leadership", "Leadership"),
                            ("language_interview", "Language Interview"),
                            ("custom", "Custom Interview"),
                        ],
                        default="behavioral",
                        max_length=30,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("job_title", models.CharField(blank=True, default="", max_length=160)),
                ("industry", models.CharField(blank=True, default="", max_length=120)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("question_count", models.PositiveSmallIntegerField(default=6)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_interview_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_interview_templates",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "ai_interview_templates",
            },
        ),
        migrations.AddIndex(
            model_name="aiinterviewsession",
            index=models.Index(
                fields=["user", "status", "created_at"], name="ai_int_user_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiinterviewsession",
            index=models.Index(
                fields=["organization", "status"], name="ai_int_org_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiinterviewsession",
            index=models.Index(
                fields=["session_type", "difficulty"], name="ai_int_type_diff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiinterviewquestion",
            index=models.Index(
                fields=["session", "sequence"], name="ai_int_question_seq_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aiinterviewquestion",
            unique_together={("session", "sequence")},
        ),
        migrations.AddIndex(
            model_name="aiinterviewanswerevaluation",
            index=models.Index(
                fields=["session", "created_at"], name="ai_int_eval_session_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiinterviewanswerevaluation",
            index=models.Index(fields=["overall_score"], name="ai_int_eval_score_idx"),
        ),
        migrations.AddIndex(
            model_name="aiinterviewtemplate",
            index=models.Index(
                fields=["organization", "is_active"], name="ai_int_tpl_org_active_idx"
            ),
        ),
    ]
