# Generated by Django 5.0.6 on 2026-07-07 22:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_platform", "0004_aievaluationdataset_dataset_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRedTeamSuite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160, unique=True)),
                (
                    "suite_type",
                    models.CharField(
                        choices=[
                            ("prompt_injection", "Prompt Injection"),
                            ("jailbreak", "Jailbreak"),
                            ("malicious_resume", "Malicious Resume"),
                            ("malicious_portfolio", "Malicious Portfolio"),
                            (
                                "malicious_interview_answer",
                                "Malicious Interview Answer",
                            ),
                            ("unsafe_url", "Unsafe URL"),
                            ("hidden_instruction", "Hidden Instruction"),
                            ("rag_poisoning", "RAG Poisoning"),
                            ("pii_leakage", "PII Leakage"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("resume_review", "Resume Review"),
                            ("portfolio_review", "Portfolio Review"),
                            ("career_advice", "Career Advice"),
                            ("learning_recommendations", "Learning Recommendations"),
                            ("job_matching", "Job Matching"),
                            ("course_tutor", "Course Tutor"),
                            ("interview_coach", "Interview Coach"),
                            ("skill_gap_analysis", "Skill Gap Analysis"),
                            ("application_review", "Application Review"),
                            ("cover_letter", "Cover Letter"),
                        ],
                        db_index=True,
                        default="chat",
                        max_length=50,
                    ),
                ),
                ("cases", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "ai_red_team_suites",
            },
        ),
        migrations.AddField(
            model_name="aievaluationdataset",
            name="difficulty",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="aievaluationdataset",
            name="expected_score_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="aievaluationdataset",
            name="expected_score_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="aievaluationdataset",
            name="locale",
            field=models.CharField(db_index=True, default="en", max_length=20),
        ),
        migrations.AddField(
            model_name="aievaluationdataset",
            name="reviewer_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="aievaluationdataset",
            name="risk_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="aievaluationdataset",
            name="rubric",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="aievaluationdataset",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("archived", "Archived"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="aievaluationrun",
            name="aggregate_results",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="aievaluationrun",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aievaluationrun",
            name="duration_seconds",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="aievaluationrun",
            name="failure_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="aievaluationrun",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="aievaluationdataset",
            name="dataset_type",
            field=models.CharField(
                choices=[
                    ("resume_intelligence", "Resume Intelligence"),
                    ("portfolio_intelligence", "Portfolio Intelligence"),
                    ("interview_coach", "Interview Coach"),
                    ("career_coach", "Career Coach"),
                    ("learning_tutor", "Learning Tutor"),
                    ("job_matching", "Job Matching"),
                    ("skill_extraction", "Skill Extraction"),
                    ("prompt_security", "Prompt Security"),
                    ("privacy_dlp", "Privacy DLP"),
                    ("fairness", "Fairness"),
                    ("hallucination", "Hallucination"),
                ],
                db_index=True,
                default="resume_intelligence",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="AIAuditExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "export_type",
                    models.CharField(
                        choices=[
                            ("evaluation_runs", "Evaluation Runs"),
                            ("safety_events", "Safety Events"),
                            ("privacy_events", "Privacy Events"),
                            ("bias_events", "Bias Events"),
                            ("feedback", "Feedback"),
                            ("provider_usage", "Provider Usage"),
                            ("prompt_versions", "Prompt Versions"),
                            ("model_comparisons", "Model Comparisons"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        choices=[("csv", "CSV"), ("xlsx", "XLSX")],
                        default="csv",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="ai-audit-exports/"
                    ),
                ),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("failure_reason", models.TextField(blank=True, default="")),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_audit_exports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_audit_exports",
                "indexes": [
                    models.Index(
                        fields=["export_type", "status", "created_at"],
                        name="ai_export_type_status_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIComparisonReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comparison_type",
                    models.CharField(
                        choices=[
                            ("provider", "Provider"),
                            ("model", "Model"),
                            ("prompt_version", "Prompt Version"),
                            ("feature_version", "Feature Version"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("resume_review", "Resume Review"),
                            ("portfolio_review", "Portfolio Review"),
                            ("career_advice", "Career Advice"),
                            ("learning_recommendations", "Learning Recommendations"),
                            ("job_matching", "Job Matching"),
                            ("course_tutor", "Course Tutor"),
                            ("interview_coach", "Interview Coach"),
                            ("skill_gap_analysis", "Skill Gap Analysis"),
                            ("application_review", "Application Review"),
                            ("cover_letter", "Cover Letter"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("left_label", models.CharField(max_length=160)),
                ("right_label", models.CharField(max_length=160)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("winner", models.CharField(blank=True, default="", max_length=160)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_comparison_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_comparison_reports",
                "indexes": [
                    models.Index(
                        fields=["comparison_type", "feature", "created_at"],
                        name="ai_compare_type_feature_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIEvaluationReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("auto_reviewed", "Auto Reviewed"),
                            ("manual_review", "Manual Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=30,
                    ),
                ),
                (
                    "manual_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "hallucination_flag",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("bias_flag", models.BooleanField(db_index=True, default=False)),
                ("unsafe_flag", models.BooleanField(db_index=True, default=False)),
                (
                    "request_prompt_revision",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_ai_evaluation_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="ai_platform.aievaluationresult",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_ai_evaluation_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_evaluation_reviews",
                "indexes": [
                    models.Index(
                        fields=["status", "assigned_to"],
                        name="ai_eval_review_queue_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIRedTeamResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("case_name", models.CharField(blank=True, default="", max_length=160)),
                ("input_text", models.TextField()),
                ("output_text", models.TextField(blank=True, default="")),
                (
                    "risk_severity",
                    models.CharField(db_index=True, default="low", max_length=20),
                ),
                ("risk_flags", models.JSONField(blank=True, default=list)),
                ("passed", models.BooleanField(db_index=True, default=True)),
                ("mitigation_notes", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="red_team_results",
                        to="ai_platform.aievaluationrun",
                    ),
                ),
                (
                    "suite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="ai_platform.airedteamsuite",
                    ),
                ),
            ],
            options={
                "db_table": "ai_red_team_results",
                "indexes": [
                    models.Index(
                        fields=["suite", "risk_severity", "passed"],
                        name="ai_red_team_suite_risk_idx",
                    )
                ],
            },
        ),
    ]
