# Generated by Django 5.0.6 on 2026-07-07 23:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_platform", "0006_alter_aievaluationdataset_dataset_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="airedteamresult",
            name="expected_safe_behavior",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="airedteamsuite",
            name="expected_safe_behavior",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="airedteamsuite",
            name="severity",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                db_index=True,
                default="medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="airedteamresult",
            name="risk_severity",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("critical", "Critical"),
                ],
                db_index=True,
                default="low",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="airedteamsuite",
            name="suite_type",
            field=models.CharField(
                choices=[
                    ("prompt_injection", "Prompt Injection"),
                    ("jailbreak", "Jailbreak"),
                    ("malicious_resume", "Malicious Resume"),
                    ("malicious_portfolio", "Malicious Portfolio"),
                    ("malicious_interview_answer", "Malicious Interview Answer"),
                    ("unsafe_url", "Unsafe URL"),
                    ("hidden_instruction", "Hidden Instruction"),
                    ("rag_poisoning", "RAG Poisoning"),
                    ("pii_leakage", "PII Leakage"),
                    ("bias_trigger", "Bias Trigger"),
                    ("hallucination_trap", "Hallucination Trap"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="AIReleaseGate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("prompt_template", "Prompt Template"),
                            ("model_configuration", "Model Configuration"),
                            ("provider", "Provider"),
                            ("feature_flag", "Feature Flag"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("target_id", models.CharField(db_index=True, max_length=100)),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("resume_review", "Resume Review"),
                            ("portfolio_review", "Portfolio Review"),
                            ("career_advice", "Career Advice"),
                            ("learning_recommendations", "Learning Recommendations"),
                            ("job_matching", "Job Matching"),
                            ("course_tutor", "Course Tutor"),
                            ("interview_coach", "Interview Coach"),
                            ("skill_gap_analysis", "Skill Gap Analysis"),
                            ("application_review", "Application Review"),
                            ("cover_letter", "Cover Letter"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("promoted", "Promoted"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("previous_version", models.JSONField(blank=True, default=dict)),
                ("new_version", models.JSONField(blank=True, default=dict)),
                ("thresholds", models.JSONField(blank=True, default=dict)),
                ("gate_results", models.JSONField(blank=True, default=dict)),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                ("rolled_back_at", models.DateTimeField(blank=True, null=True)),
                ("rollback_reason", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "evaluation_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="release_gates",
                        to="ai_platform.aievaluationrun",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_ai_release_gates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_ai_release_gates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_release_gates",
            },
        ),
        migrations.CreateModel(
            name="AIChangeHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("prompt_template", "Prompt Template"),
                            ("model_configuration", "Model Configuration"),
                            ("provider", "Provider"),
                            ("feature_flag", "Feature Flag"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("target_id", models.CharField(db_index=True, max_length=100)),
                ("previous_version", models.JSONField(blank=True, default=dict)),
                ("new_version", models.JSONField(blank=True, default=dict)),
                (
                    "approval_state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_review", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("promoted", "Promoted"),
                            ("rolled_back", "Rolled Back"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=30,
                    ),
                ),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                ("rolled_back_at", models.DateTimeField(blank=True, null=True)),
                ("rollback_reason", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_change_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evaluation_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="change_history",
                        to="ai_platform.aievaluationrun",
                    ),
                ),
                (
                    "gate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_history",
                        to="ai_platform.aireleasegate",
                    ),
                ),
            ],
            options={
                "db_table": "ai_change_history",
            },
        ),
        migrations.AddIndex(
            model_name="aireleasegate",
            index=models.Index(
                fields=["feature", "status", "change_type"],
                name="ai_release_feature_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aichangehistory",
            index=models.Index(
                fields=["change_type", "approval_state", "created_at"],
                name="ai_change_type_state_idx",
            ),
        ),
    ]
