# Generated by Django 5.0.6 on 2026-07-08 10:43

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_platform", "0007_airedteamresult_expected_safe_behavior_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AICareerGoal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=160)),
                ("target_role", models.CharField(db_index=True, max_length=160)),
                (
                    "target_industry",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                (
                    "target_country",
                    models.CharField(blank=True, default="", max_length=2),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("progress_percentage", models.PositiveSmallIntegerField(default=0)),
                ("milestones", models.JSONField(blank=True, default=list)),
                ("completed_milestones", models.JSONField(blank=True, default=list)),
                ("coaching_history", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_career_goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_career_goals",
            },
        ),
        migrations.CreateModel(
            name="AICareerCoachingSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("week_start", models.DateField(db_index=True)),
                ("summary", models.TextField(blank=True, default="")),
                ("achievements", models.JSONField(blank=True, default=list)),
                ("missed_goals", models.JSONField(blank=True, default=list)),
                ("recommended_actions", models.JSONField(blank=True, default=list)),
                ("upcoming_priorities", models.JSONField(blank=True, default=list)),
                ("motivation_summary", models.TextField(blank=True, default="")),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="career_coaching_summaries",
                        to="ai_platform.airequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_career_coaching_summaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coaching_summaries",
                        to="ai_platform.aicareergoal",
                    ),
                ),
            ],
            options={
                "db_table": "ai_career_coaching_summaries",
            },
        ),
        migrations.CreateModel(
            name="AICareerAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "readiness_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("strengths", models.JSONField(blank=True, default=list)),
                ("weaknesses", models.JSONField(blank=True, default=list)),
                ("growth_opportunities", models.JSONField(blank=True, default=list)),
                ("recommendations", models.JSONField(blank=True, default=list)),
                ("assessment", models.JSONField(blank=True, default=dict)),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "prompt_version",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=12
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="career_assessments",
                        to="ai_platform.airequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_career_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessments",
                        to="ai_platform.aicareergoal",
                    ),
                ),
            ],
            options={
                "db_table": "ai_career_assessments",
            },
        ),
        migrations.CreateModel(
            name="AICareerRoadmap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "horizon",
                    models.CharField(
                        choices=[
                            ("3_months", "3 Months"),
                            ("6_months", "6 Months"),
                            ("12_months", "12 Months"),
                            ("24_months", "24 Months"),
                        ],
                        db_index=True,
                        default="6_months",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=180)),
                ("roadmap", models.JSONField(blank=True, default=dict)),
                ("milestones", models.JSONField(blank=True, default=list)),
                ("recommended_courses", models.JSONField(blank=True, default=list)),
                ("recommended_projects", models.JSONField(blank=True, default=list)),
                ("progress_percentage", models.PositiveSmallIntegerField(default=0)),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=12
                    ),
                ),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roadmaps",
                        to="ai_platform.aicareergoal",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="career_roadmaps",
                        to="ai_platform.airequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_career_roadmaps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_career_roadmaps",
            },
        ),
        migrations.CreateModel(
            name="AICareerSkillGap",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comparison_type",
                    models.CharField(
                        db_index=True, default="career_goal", max_length=40
                    ),
                ),
                ("target", models.CharField(blank=True, default="", max_length=180)),
                ("missing_skills", models.JSONField(blank=True, default=list)),
                ("priority_skills", models.JSONField(blank=True, default=list)),
                ("estimated_learning_time", models.JSONField(blank=True, default=dict)),
                ("recommended_courses", models.JSONField(blank=True, default=list)),
                ("recommended_projects", models.JSONField(blank=True, default=list)),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("report", models.JSONField(blank=True, default=dict)),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="skill_gaps",
                        to="ai_platform.aicareergoal",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="career_skill_gaps",
                        to="ai_platform.airequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_career_skill_gaps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_career_skill_gaps",
            },
        ),
        migrations.AddIndex(
            model_name="aicareergoal",
            index=models.Index(
                fields=["user", "status"], name="ai_goal_user_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aicareercoachingsummary",
            index=models.Index(
                fields=["user", "week_start"], name="ai_coach_user_week_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aicareerassessment",
            index=models.Index(
                fields=["user", "created_at"], name="ai_career_assess_user_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aicareerroadmap",
            index=models.Index(
                fields=["user", "horizon", "created_at"],
                name="ai_road_user_horizon_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aicareerskillgap",
            index=models.Index(
                fields=["user", "comparison_type", "created_at"],
                name="ai_gap_user_type_idx",
            ),
        ),
    ]
