# Generated by Django 5.0.6 on 2026-07-08 12:45

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_platform", "0008_aicareergoal_aicareercoachingsummary_and_more"),
        ("jobs", "0009_jobapplicationquestion_jobapplicationanswer_and_more"),
        ("organizations", "0007_dataexportjob_file_deleted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRecruiterReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("candidate_analysis", "Candidate Analysis"),
                            ("candidate_ranking", "Candidate Ranking"),
                            ("candidate_comparison", "Candidate Comparison"),
                            ("job_analysis", "Job Analysis"),
                            ("interview_plan", "Interview Plan"),
                            ("pipeline_insights", "Pipeline Insights"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=180)),
                (
                    "score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("candidate_ids", models.JSONField(blank=True, default=list)),
                ("report", models.JSONField(blank=True, default=dict)),
                ("fairness_notes", models.TextField(blank=True, default="")),
                (
                    "disclaimer",
                    models.TextField(
                        blank=True,
                        default="AI assistance is advisory. Do not automatically reject candidates or make hiring decisions solely from AI output.",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=12
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_recruiter_candidate_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_recruiter_reports",
                        to="jobs.joblisting",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_recruiter_reports",
                        to="organizations.organization",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recruiter_reports",
                        to="ai_platform.airequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_recruiter_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_recruiter_reports",
                "indexes": [
                    models.Index(
                        fields=["user", "report_type", "created_at"],
                        name="ai_rec_user_type_idx",
                    ),
                    models.Index(
                        fields=["organization", "report_type"],
                        name="ai_rec_org_type_idx",
                    ),
                ],
            },
        ),
    ]
