# Generated by Django 5.0.6 on 2026-07-08 16:04

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_platform", "0009_airecruiterreport"),
        ("assessments", "0001_initial"),
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIGeneratedQuiz",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        db_index=True,
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("question_count", models.PositiveSmallIntegerField(default=5)),
                ("learning_objectives", models.JSONField(blank=True, default=list)),
                ("questions", models.JSONField(blank=True, default=list)),
                (
                    "is_instructor_reviewed",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "is_published_to_students",
                    models.BooleanField(db_index=True, default=False),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=12
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_generated_quizzes",
                        to="courses.course",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_generated_quizzes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_generated_quizzes",
                        to="courses.lesson",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_quizzes",
                        to="ai_platform.airequest",
                    ),
                ),
            ],
            options={
                "db_table": "ai_generated_quizzes",
                "indexes": [
                    models.Index(
                        fields=["course", "lesson", "created_at"],
                        name="ai_quiz_course_less_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AILearningTutorSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question", models.TextField(blank=True, default="")),
                ("answer", models.TextField(blank=True, default="")),
                (
                    "mode",
                    models.CharField(db_index=True, default="question", max_length=40),
                ),
                ("context", models.JSONField(blank=True, default=dict)),
                ("concepts", models.JSONField(blank=True, default=list)),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=12
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_tutor_sessions",
                        to="courses.course",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_tutor_sessions",
                        to="courses.lesson",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="learning_tutor_sessions",
                        to="ai_platform.airequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_learning_tutor_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_learning_tutor_sessions",
                "indexes": [
                    models.Index(
                        fields=["user", "course", "created_at"],
                        name="ai_tutor_user_course_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AILessonIntelligence",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                ("summary", models.TextField(blank=True, default="")),
                ("key_concepts", models.JSONField(blank=True, default=list)),
                ("glossary", models.JSONField(blank=True, default=dict)),
                ("important_formulas", models.JSONField(blank=True, default=list)),
                ("common_mistakes", models.JSONField(blank=True, default=list)),
                ("prerequisites", models.JSONField(blank=True, default=list)),
                ("learning_objectives", models.JSONField(blank=True, default=list)),
                (
                    "estimated_study_time_minutes",
                    models.PositiveIntegerField(default=0),
                ),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=12
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_lesson_intelligence",
                        to="courses.course",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_lesson_intelligence_generated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_intelligence_reports",
                        to="courses.lesson",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lesson_intelligence_reports",
                        to="ai_platform.airequest",
                    ),
                ),
            ],
            options={
                "db_table": "ai_lesson_intelligence",
                "indexes": [
                    models.Index(
                        fields=["lesson", "is_current"], name="ai_lesson_current_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIQuizFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("explanation", models.TextField(blank=True, default="")),
                ("correct_reasoning", models.JSONField(blank=True, default=list)),
                ("weak_topics", models.JSONField(blank=True, default=list)),
                ("recommended_lessons", models.JSONField(blank=True, default=list)),
                ("next_actions", models.JSONField(blank=True, default=list)),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=12
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_quiz_feedback",
                        to="courses.course",
                    ),
                ),
                (
                    "quiz_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_feedback",
                        to="assessments.quizattempt",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quiz_feedback",
                        to="ai_platform.airequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_quiz_feedback",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_quiz_feedback",
                "indexes": [
                    models.Index(
                        fields=["user", "course", "created_at"],
                        name="ai_feedback_user_course_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIStudyPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cadence",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        db_index=True,
                        default="weekly",
                        max_length=20,
                    ),
                ),
                (
                    "pace",
                    models.CharField(
                        choices=[
                            ("relaxed", "Relaxed"),
                            ("balanced", "Balanced"),
                            ("intensive", "Intensive"),
                        ],
                        default="balanced",
                        max_length=20,
                    ),
                ),
                ("available_minutes_per_day", models.PositiveIntegerField(default=60)),
                ("deadline", models.DateField(blank=True, null=True)),
                ("title", models.CharField(blank=True, default="", max_length=180)),
                ("plan", models.JSONField(blank=True, default=dict)),
                ("milestones", models.JSONField(blank=True, default=list)),
                ("weak_concepts", models.JSONField(blank=True, default=list)),
                ("recommended_lessons", models.JSONField(blank=True, default=list)),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        decimal_places=6, default=Decimal("0.000000"), max_digits=12
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="study_plans",
                        to="ai_platform.airequest",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_study_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_study_plans",
                "indexes": [
                    models.Index(
                        fields=["user", "cadence", "created_at"],
                        name="ai_plan_user_cad_idx",
                    )
                ],
            },
        ),
    ]
