# Generated by Django 5.0.6 on 2026-07-08 16:40

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_platform", "0010_aigeneratedquiz_ailearningtutorsession_and_more"),
        ("organizations", "0007_dataexportjob_file_deleted_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeCollection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                (
                    "collection_type",
                    models.CharField(
                        choices=[
                            ("courses", "Courses"),
                            ("lessons", "Lessons"),
                            ("quizzes", "Quizzes"),
                            ("career_tracks", "Career Tracks"),
                            ("resumes", "Resumes"),
                            ("portfolios", "Portfolios"),
                            ("jobs", "Jobs"),
                            ("skills", "Skills"),
                            ("certificates", "Certificates"),
                            ("faqs", "FAQs"),
                            ("policies", "Policies"),
                            ("organization_documents", "Organization Documents"),
                            ("future_documents", "Future Documents"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "embedding_version",
                    models.CharField(
                        db_index=True, default="deterministic-v1", max_length=120
                    ),
                ),
                (
                    "vector_backend",
                    models.CharField(db_index=True, default="local", max_length=40),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_collections",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "ai_knowledge_collections",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_type", models.CharField(db_index=True, max_length=60)),
                ("source_id", models.CharField(db_index=True, max_length=120)),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("text", models.TextField()),
                ("redacted_text", models.TextField(blank=True, default="")),
                (
                    "version",
                    models.CharField(db_index=True, default="1", max_length=80),
                ),
                ("checksum", models.CharField(db_index=True, max_length=64)),
                (
                    "embedding_version",
                    models.CharField(
                        db_index=True, default="deterministic-v1", max_length=120
                    ),
                ),
                (
                    "index_status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("indexing", "Indexing"),
                            ("indexed", "Indexed"),
                            ("failed", "Failed"),
                            ("stale", "Stale"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("organization", "Organization"),
                            ("private", "Private"),
                        ],
                        db_index=True,
                        default="public",
                        max_length=20,
                    ),
                ),
                ("last_indexed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, default="")),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="ai_platform.knowledgecollection",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_documents",
                        to="organizations.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="knowledge_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_knowledge_documents",
            },
        ),
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("chunk_index", models.PositiveIntegerField()),
                ("text", models.TextField()),
                ("embedding", models.JSONField(blank=True, default=list)),
                ("token_count", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="ai_platform.knowledgedocument",
                    ),
                ),
            ],
            options={
                "db_table": "ai_knowledge_chunks",
            },
        ),
        migrations.CreateModel(
            name="RetrievalEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("resume_review", "Resume Review"),
                            ("portfolio_review", "Portfolio Review"),
                            ("career_advice", "Career Advice"),
                            ("learning_recommendations", "Learning Recommendations"),
                            ("job_matching", "Job Matching"),
                            ("course_tutor", "Course Tutor"),
                            ("interview_coach", "Interview Coach"),
                            ("skill_gap_analysis", "Skill Gap Analysis"),
                            ("application_review", "Application Review"),
                            ("cover_letter", "Cover Letter"),
                        ],
                        db_index=True,
                        default="chat",
                        max_length=50,
                    ),
                ),
                ("query", models.TextField()),
                (
                    "search_type",
                    models.CharField(db_index=True, default="hybrid", max_length=30),
                ),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("result_count", models.PositiveIntegerField(default=0)),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("cache_hit", models.BooleanField(db_index=True, default=False)),
                ("sources", models.JSONField(blank=True, default=list)),
                ("missing_knowledge", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_retrieval_events",
                        to="organizations.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_retrieval_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_retrieval_events",
            },
        ),
        migrations.AddIndex(
            model_name="knowledgecollection",
            index=models.Index(
                fields=["collection_type", "is_active"],
                name="ai_know_collection_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgecollection",
            index=models.Index(
                fields=["organization", "collection_type"],
                name="ai_know_collection_org_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="knowledgecollection",
            unique_together={("collection_type", "organization", "embedding_version")},
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["collection", "index_status"], name="ai_know_doc_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["source_type", "source_id"], name="ai_know_doc_source_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["organization", "visibility"], name="ai_know_doc_org_vis_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="knowledgedocument",
            index=models.Index(
                fields=["embedding_version", "index_status"],
                name="ai_know_doc_embed_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="knowledgedocument",
            unique_together={("collection", "source_type", "source_id")},
        ),
        migrations.AddIndex(
            model_name="knowledgechunk",
            index=models.Index(
                fields=["document", "chunk_index"], name="ai_know_chunk_order_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="knowledgechunk",
            unique_together={("document", "chunk_index")},
        ),
        migrations.AddIndex(
            model_name="retrievalevent",
            index=models.Index(
                fields=["feature", "created_at"], name="ai_retrieval_feature_date_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="retrievalevent",
            index=models.Index(
                fields=["organization", "feature"], name="ai_retrieval_org_feature_idx"
            ),
        ),
    ]
