# Generated by Django 5.0.6 on 2026-07-08 20:35

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ai_platform",
            "0011_knowledgecollection_knowledgedocument_knowledgechunk_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RetrievalEvaluationDataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160, unique=True)),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("chat", "Chat"),
                            ("resume_review", "Resume Review"),
                            ("portfolio_review", "Portfolio Review"),
                            ("career_advice", "Career Advice"),
                            ("learning_recommendations", "Learning Recommendations"),
                            ("job_matching", "Job Matching"),
                            ("course_tutor", "Course Tutor"),
                            ("interview_coach", "Interview Coach"),
                            ("skill_gap_analysis", "Skill Gap Analysis"),
                            ("application_review", "Application Review"),
                            ("cover_letter", "Cover Letter"),
                        ],
                        db_index=True,
                        default="chat",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("cases", models.JSONField(blank=True, default=list)),
                (
                    "minimum_pass_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.80"), max_digits=5
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "ai_retrieval_evaluation_datasets",
            },
        ),
        migrations.AddField(
            model_name="knowledgecollection",
            name="health_status",
            field=models.CharField(db_index=True, default="unknown", max_length=30),
        ),
        migrations.AddField(
            model_name="knowledgecollection",
            name="last_health_check_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgecollection",
            name="last_health_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="knowledgecollection",
            name="vector_dimensions",
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="freshness_score",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=5
            ),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="last_successful_reindex_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="source_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgedocument",
            name="stale_reason",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="retrievalevent",
            name="chunk_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="retrievalevent",
            name="context_size",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="retrievalevent",
            name="source_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="retrievalevent",
            name="timed_out",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name="RetrievalEvaluationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("total_cases", models.PositiveIntegerField(default=0)),
                ("passed_cases", models.PositiveIntegerField(default=0)),
                ("failed_cases", models.PositiveIntegerField(default=0)),
                (
                    "pass_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "average_confidence",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("report", models.JSONField(blank=True, default=dict)),
                ("failure_reason", models.TextField(blank=True, default="")),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="ai_platform.retrievalevaluationdataset",
                    ),
                ),
                (
                    "run_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_retrieval_evaluation_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ai_retrieval_evaluation_runs",
            },
        ),
        migrations.CreateModel(
            name="RetrievalEvaluationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query", models.TextField()),
                (
                    "expected_document_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "expected_chunk_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "expected_source_type",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("expected_citation", models.JSONField(blank=True, default=dict)),
                (
                    "minimum_confidence",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "ranking_position",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("passed", models.BooleanField(db_index=True, default=False)),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                ("retrieved_citations", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="ai_platform.retrievalevaluationrun",
                    ),
                ),
            ],
            options={
                "db_table": "ai_retrieval_evaluation_results",
                "indexes": [
                    models.Index(
                        fields=["run", "passed"], name="ai_retrieval_eval_pass_idx"
                    )
                ],
            },
        ),
    ]
