# Generated by Django 5.0.6 on 2026-07-03 14:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_recruiter_entitlements_candidate_unlocks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cohort",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "academic_year",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("semester", models.CharField(blank=True, default="", max_length=50)),
                ("batch", models.CharField(blank=True, default="", max_length=100)),
                ("program", models.CharField(blank=True, default="", max_length=255)),
                (
                    "graduation_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("enrollment_starts_at", models.DateField(blank=True, null=True)),
                ("enrollment_ends_at", models.DateField(blank=True, null=True)),
                ("assigned_course_ids", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohorts",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organization_cohorts",
            },
        ),
        migrations.CreateModel(
            name="CohortMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("manager", "Manager"),
                            ("admin", "Admin"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="organizations.cohort",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cohort_memberships",
                        to="organizations.organizationmembership",
                    ),
                ),
            ],
            options={
                "db_table": "organization_cohort_members",
            },
        ),
        migrations.CreateModel(
            name="DataExportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("export_type", models.CharField(max_length=40)),
                ("file_format", models.CharField(default="csv", max_length=10)),
                ("row_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(db_index=True, default="generated", max_length=30),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_exports",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organization_data_export_jobs",
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organization_departments",
            },
        ),
        migrations.CreateModel(
            name="DepartmentMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("manager", "Manager"),
                            ("admin", "Admin"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="organizations.department",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="department_memberships",
                        to="organizations.organizationmembership",
                    ),
                ),
            ],
            options={
                "db_table": "organization_department_members",
            },
        ),
        migrations.CreateModel(
            name="OrganizationPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("password_min_length", models.PositiveSmallIntegerField(default=8)),
                ("mfa_required", models.BooleanField(default=False)),
                ("profile_visibility_default", models.BooleanField(default=True)),
                ("resume_visibility_default", models.BooleanField(default=True)),
                ("portfolio_visibility_default", models.BooleanField(default=True)),
                (
                    "invitation_expiration_days",
                    models.PositiveSmallIntegerField(default=7),
                ),
                ("session_timeout_minutes", models.PositiveIntegerField(default=480)),
                ("allowed_email_domains", models.JSONField(blank=True, default=list)),
                ("recruiter_permissions", models.JSONField(blank=True, default=dict)),
                ("student_permissions", models.JSONField(blank=True, default=dict)),
                ("notification_defaults", models.JSONField(blank=True, default=dict)),
                (
                    "digest_frequency",
                    models.CharField(blank=True, default="weekly", max_length=30),
                ),
                ("quiet_hours", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organization_policies",
            },
        ),
        migrations.CreateModel(
            name="OrganizationProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("logo_url", models.URLField(blank=True, default="")),
                ("banner_url", models.URLField(blank=True, default="")),
                ("favicon_url", models.URLField(blank=True, default="")),
                (
                    "primary_color",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "secondary_color",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "support_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "support_phone",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "time_zone",
                    models.CharField(blank=True, default="UTC", max_length=80),
                ),
                (
                    "default_language",
                    models.CharField(blank=True, default="en", max_length=10),
                ),
                ("email_branding", models.JSONField(blank=True, default=dict)),
                ("certificate_branding", models.JSONField(blank=True, default=dict)),
                ("landing_page_branding", models.JSONField(blank=True, default=dict)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enterprise_profile",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organization_enterprise_profiles",
            },
        ),
        migrations.CreateModel(
            name="OrganizationTeam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "team_type",
                    models.CharField(
                        choices=[
                            ("recruiting", "Recruiting Team"),
                            ("instructor", "Instructor Team"),
                            ("career", "Career Team"),
                            ("placement", "Placement Team"),
                            ("admissions", "Admissions Team"),
                            ("operations", "Operations Team"),
                            ("finance", "Finance Team"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("archived", "Archived")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                ("permissions", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="managed_teams",
                        to="organizations.organizationmembership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organization_teams",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("manager", "Manager"),
                            ("admin", "Admin"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_memberships",
                        to="organizations.organizationmembership",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="organizations.organizationteam",
                    ),
                ),
            ],
            options={
                "db_table": "organization_team_members",
            },
        ),
        migrations.CreateModel(
            name="BulkImportJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("students", "Students"),
                            ("recruiters", "Recruiters"),
                            ("instructors", "Instructors"),
                            ("employees", "Employees"),
                            ("departments", "Departments"),
                            ("teams", "Teams"),
                            ("skills", "Skills"),
                            ("course_assignments", "Course Assignments"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(db_index=True, default="previewed", max_length=30),
                ),
                (
                    "source_filename",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("preview_rows", models.JSONField(blank=True, default=list)),
                ("validation_errors", models.JSONField(blank=True, default=list)),
                ("success_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bulk_imports",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organization_bulk_import_jobs",
                "indexes": [
                    models.Index(
                        fields=["organization", "import_type", "status"],
                        name="org_bulk_type_status_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="cohort",
            index=models.Index(
                fields=["organization", "status"], name="org_cohort_org_status_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cohort",
            unique_together={("organization", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="cohortmember",
            unique_together={("cohort", "membership")},
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["organization", "status"], name="org_dept_org_status_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("organization", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="departmentmember",
            unique_together={("department", "membership")},
        ),
        migrations.AddIndex(
            model_name="organizationteam",
            index=models.Index(
                fields=["organization", "team_type", "status"],
                name="org_team_type_status_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="organizationteam",
            unique_together={("organization", "name")},
        ),
        migrations.AlterUniqueTogether(
            name="teammember",
            unique_together={("team", "membership")},
        ),
    ]
