# Generated by Django 5.0.6 on 2026-07-03 15:23

import apps.organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_cohort_cohortmember_dataexportjob_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkimportjob",
            name="error_report",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="bulkimportjob",
            name="partial_success_report",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="bulkimportjob",
            name="required_columns",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="dataexportjob",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dataexportjob",
            name="content_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="dataexportjob",
            name="failed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dataexportjob",
            name="file",
            field=models.FileField(
                blank=True,
                default="",
                upload_to=apps.organizations.models.organization_export_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="dataexportjob",
            name="file_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="dataexportjob",
            name="file_size",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dataexportjob",
            name="last_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="banner",
            field=models.FileField(
                blank=True,
                default="",
                upload_to=apps.organizations.models.organization_branding_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="certificate_logo",
            field=models.FileField(
                blank=True,
                default="",
                upload_to=apps.organizations.models.organization_branding_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="email_header_image",
            field=models.FileField(
                blank=True,
                default="",
                upload_to=apps.organizations.models.organization_branding_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="favicon",
            field=models.FileField(
                blank=True,
                default="",
                upload_to=apps.organizations.models.organization_branding_upload_path,
            ),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="logo",
            field=models.FileField(
                blank=True,
                default="",
                upload_to=apps.organizations.models.organization_branding_upload_path,
            ),
        ),
        migrations.AlterField(
            model_name="bulkimportjob",
            name="import_type",
            field=models.CharField(
                choices=[
                    ("students", "Students"),
                    ("recruiters", "Recruiters"),
                    ("instructors", "Instructors"),
                    ("employees", "Employees"),
                    ("departments", "Departments"),
                    ("teams", "Teams"),
                    ("cohorts", "Cohorts"),
                    ("skills", "Skills"),
                    ("course_assignments", "Course Assignments"),
                    ("cohort_assignments", "Cohort Assignments"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="dataexportjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("queued", "Queued"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="queued",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="organizationinvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("instructor", "Instructor"),
                    ("mentor", "Mentor"),
                    ("recruiter", "Recruiter"),
                    ("company_admin", "Company Admin"),
                    ("university_admin", "University Admin"),
                    ("content_moderator", "Content Moderator"),
                    ("finance_admin", "Finance Admin"),
                    ("platform_admin", "Platform Admin"),
                    ("super_admin", "Super Admin"),
                    ("report_viewer", "Report Viewer"),
                    ("department_manager", "Department Manager"),
                    ("cohort_manager", "Cohort Manager"),
                    ("team_manager", "Team Manager"),
                    ("export_manager", "Export Manager"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="organizationmembership",
            name="role",
            field=models.CharField(
                choices=[
                    ("student", "Student"),
                    ("instructor", "Instructor"),
                    ("mentor", "Mentor"),
                    ("recruiter", "Recruiter"),
                    ("company_admin", "Company Admin"),
                    ("university_admin", "University Admin"),
                    ("content_moderator", "Content Moderator"),
                    ("finance_admin", "Finance Admin"),
                    ("platform_admin", "Platform Admin"),
                    ("super_admin", "Super Admin"),
                    ("report_viewer", "Report Viewer"),
                    ("department_manager", "Department Manager"),
                    ("cohort_manager", "Cohort Manager"),
                    ("team_manager", "Team Manager"),
                    ("export_manager", "Export Manager"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
    ]
