# Generated by Django 5.0.6 on 2026-07-03 22:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_bulkimportjob_completed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dataexportjob",
            name="file_deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dataexportjob",
            name="legal_hold",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="bulkimportjob",
            name="import_type",
            field=models.CharField(
                choices=[
                    ("students", "Students"),
                    ("recruiters", "Recruiters"),
                    ("instructors", "Instructors"),
                    ("employees", "Employees"),
                    ("departments", "Departments"),
                    ("teams", "Teams"),
                    ("cohorts", "Cohorts"),
                    ("skills", "Skills"),
                    ("courses", "Courses"),
                    ("course_assignments", "Course Assignments"),
                    ("cohort_assignments", "Cohort Assignments"),
                ],
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="enterprisereportjob",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("enrollment", "Enrollment"),
                    ("enrollment_report", "Enrollment Report"),
                    ("placement", "Placement"),
                    ("placement_report", "Placement Report"),
                    ("hiring", "Hiring"),
                    ("hiring_report", "Hiring Report"),
                    ("recruiter_activity", "Recruiter Activity"),
                    ("recruiter_activity_report", "Recruiter Activity Report"),
                    ("certificate_completion", "Certificate Completion"),
                    ("certificate_completion_report", "Certificate Completion Report"),
                    ("course_completion", "Course Completion"),
                    ("course_completion_report", "Course Completion Report"),
                    ("department_summary", "Department Summary"),
                    ("department_summary_report", "Department Summary Report"),
                    ("cohort_summary", "Cohort Summary"),
                    ("cohort_summary_report", "Cohort Summary Report"),
                    ("organization_summary", "Organization Summary"),
                    ("organization_summary_report", "Organization Summary Report"),
                    ("engagement_summary", "Engagement Summary"),
                    ("engagement_summary_report", "Engagement Summary Report"),
                    ("export_summary_report", "Export Summary Report"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="EnterpriseWorkerStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("worker_key", models.CharField(db_index=True, max_length=100)),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("last_successful_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_failed_run_at", models.DateTimeField(blank=True, null=True)),
                ("average_duration_seconds", models.PositiveIntegerField(default=0)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("stuck_job_count", models.PositiveIntegerField(default=0)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="worker_statuses",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "db_table": "organization_enterprise_worker_statuses",
                "indexes": [
                    models.Index(
                        fields=["organization", "worker_key"], name="org_worker_key_idx"
                    ),
                    models.Index(
                        fields=["last_heartbeat_at"], name="org_worker_heartbeat_idx"
                    ),
                ],
                "unique_together": {("worker_key", "organization")},
            },
        ),
    ]
